Repository mindsdb/mindsdb, pull requests merged in 2019-11, with the labels that each got.

#325 Add PyPI downloads
  README.md
Labels: documentation

#326 Benchmarks, version check, cahce
  mindsdb/__about__.py
  mindsdb/libs/backends/lightwood.py
  mindsdb/libs/helpers/general_helpers.py
  tests/accuracy_benchmarking/benchmark.py
  tests/accuracy_benchmarking/compare.py
Labels: bug, enhancement, refactor

#329 Data Splitter
  mindsdb/config/__init__.py
  mindsdb/libs/constants/mindsdb.py
  mindsdb/libs/controllers/predictor.py
  mindsdb/libs/controllers/transaction.py
  mindsdb/libs/helpers/general_helpers.py
  mindsdb/libs/phases/data_extractor/data_extractor.py
  mindsdb/libs/phases/data_splitter/__init__.py
  mindsdb/libs/phases/data_splitter/data_splitter.py
  mindsdb/libs/phases/model_analyzer/model_analyzer.py
  mindsdb/libs/phases/model_interface/model_interface.py
  mindsdb/libs/phases/stats_generator/stats_generator.py
  requirements.txt
  test.py
  tests/functional_testing/analyse_dataset.py
Labels: bug, enhancement, refactor

#335 Multilabel splitter fix
  mindsdb/__about__.py
  mindsdb/config/__init__.py
  mindsdb/libs/controllers/transaction.py
  mindsdb/libs/helpers/general_helpers.py
  mindsdb/libs/phases/data_transformer/data_transformer.py
  tests/accuracy_benchmarking/compare.py
  tests/ci_tests/fast_test.py
  tests/ci_tests/full_test.py
  tests/ci_tests/tests.py
Labels: bug

#337 Amd tests
  mindsdb/__about__.py
  tests/ci_tests/tests.py
Labels: tests

#338 Reduce memory consumption and increase data transformer speed
  .gitignore
  jss.py
  mindsdb/__about__.py
  mindsdb/libs/controllers/transaction.py
  mindsdb/libs/data_sources/file_ds.py
  mindsdb/libs/helpers/debugging.py
  mindsdb/libs/phases/data_extractor/data_extractor.py
  mindsdb/libs/phases/data_splitter/data_splitter.py
  mindsdb/libs/phases/data_transformer/data_transformer.py
  mindsdb/libs/phases/model_analyzer/helpers/column_evaluator.py
  mindsdb/libs/phases/stats_generator/stats_generator.py
  requirements.txt
  test.py
Labels: enhancement, refactor

#341 Test fix
  mindsdb/__about__.py
  tests/ci_tests/full_test.py
  tests/ci_tests/tests.py
Labels: bug
