Repository mindsdb/mindsdb, pull requests merged in 2020-07, with the labels that each got.

#551 Some decoupling + DatabaseWrapper + working with mindsdb_native.F
  docker-compose.yml
  mindsdb/__main__.py
  mindsdb/api/http/namespaces/predictor.py
  mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py
  mindsdb/integrations/clickhouse/__init__.py
  mindsdb/integrations/clickhouse/clickhouse.py
  mindsdb/integrations/mariadb/__init__.py
  mindsdb/integrations/mariadb/mariadb.py
  mindsdb/interfaces/database/__init__.py
  mindsdb/interfaces/database/database.py
  mindsdb/interfaces/datastore/datastore.py
  mindsdb/interfaces/datastore/sqlite_helpers.py
  mindsdb/interfaces/native/mindsdb.py
  mindsdb/interfaces/native/predictor_process.py
  mindsdb/utilities/wizards.py
  tests/docker/docker-compose.yml
  tests/ressources/cert.pem
Labels: bug, current priority, enhancement, refactor

#554 fix #550 login with empty password with auth method change
  .gitignore
  mindsdb/api/mysql/mysql_proxy/data_types/mysql_packet.py
  mindsdb/api/mysql/mysql_proxy/data_types/mysql_packets/switch_auth_response_packet.py
  mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py
  mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
  mindsdb/integrations/clickhouse/clickhouse.py
  mindsdb/interfaces/database/database.py
  mindsdb/interfaces/native/mindsdb.py
  tests/docker/cli.sh
  tests/docker/docker-compose.yml
  tests/integration_tests/common.py
  tests/integration_tests/test_mariadb.py
Labels: bug, current priority

#559 Added _max _min and _explain columns
  mindsdb/README.md
  mindsdb/api/mysql/mysql_proxy/data_types/mysql_packet.py
  mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py
  mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
  mindsdb/integrations/clickhouse/clickhouse.py
  mindsdb/integrations/mariadb/mariadb.py
  tests/integration_tests/test_mariadb.py
Labels: enhancement

#569 Ci testing
  .travis.yml
  mindsdb/__main__.py
  mindsdb/api/http/namespaces/datasource.py
  mindsdb/api/http/namespaces/predictor.py
  mindsdb/interfaces/database/database.py
  mindsdb/interfaces/datastore/datastore.py
  mindsdb/interfaces/native/mindsdb.py
  requirements.txt
  requirements_test.txt
  tests/ci_tests/__init__.py
  tests/ci_tests/test_endpoints.py
  tests/conftest.py
  tests/docker/docker-compose.yml
  tests/docker/mariadb/Dockerfile
  tests/docker/mariadb/connect.cnf
  tests/integration_tests/_test_clickhouse.py
  tests/integration_tests/_test_mariadb.py
  tests/integration_tests/api/test_http.py
  tests/integration_tests/common.py
  tests/plugin.py
Labels: bug, enhancement, tests

#572 allow returns unlimited number of packets via mysql-interface
  mindsdb/api/mysql/mysql_proxy/data_types/mysql_packet.py
  mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
Labels: bug

#571 new ssl-cert for each connection
  mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
  mindsdb/utilities/wizards.py
  requirements.txt
Labels: bug

#575 Dynamic config
  .gitignore
  .travis.yml
  mindsdb/__init__.py
  mindsdb/__main__.py
  mindsdb/api/http/namespaces/entitites/predictor_metadata.py
  mindsdb/api/http/namespaces/predictor.py
  mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py
  mindsdb/integrations/clickhouse/clickhouse.py
  mindsdb/integrations/mariadb/mariadb.py
  mindsdb/interfaces/database/database.py
  mindsdb/utilities/config.py
  mindsdb/utilities/fs.py
  mindsdb/utilities/wizards.py
  tests/conftest.py
  tests/integration_tests/_test_clickhouse.py
  tests/integration_tests/api/test_http.py
  tests/integration_tests/flows/_test_mariadb.py
  tests/integration_tests/flows/config/cert.pem
  tests/integration_tests/flows/config/config.json
  tests/integration_tests/flows/test_clickhouse.py
  tests/plugin.py
Labels: enhancement

#580 patch
  mindsdb/__main__.py
  mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py
  mindsdb/integrations/clickhouse/clickhouse.py
  mindsdb/interfaces/database/database.py
  mindsdb/interfaces/native/predictor_process.py
  requirements.txt
  tests/docker/cli.sh
Labels: bug

#587 Original target + removals
  mindsdb/__main__.py
  mindsdb/api/mysql/mysql_proxy/datahub/datahub.py
  mindsdb/api/mysql/mysql_proxy/datahub/datanodes/csv_datanode.py
  mindsdb/api/mysql/mysql_proxy/datahub/datanodes/fake_datanode.py
  mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py
  mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mongo_datanode.py
  mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
  mindsdb/integrations/clickhouse/clickhouse.py
  mindsdb/integrations/mariadb/mariadb.py
  mindsdb/interfaces/native/predictor_process.py
Labels: enhancement, refactor

#589 Tests update
  .travis.yml
  mindsdb/api/http/start.py
  requirements_test.txt
  tests/integration_tests/common.py
  tests/integration_tests/flows/common.py
  tests/integration_tests/flows/config/config.json
  tests/integration_tests/flows/test_clickhouse.py
  tests/integration_tests/flows/test_mariadb.py
Labels: tests

#594 Capture information about
  mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
  mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py
  mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
  mindsdb/integrations/clickhouse/clickhouse.py
  mindsdb/integrations/mariadb/mariadb.py
Labels: current priority, enhancement

#595 External data query
  mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
  mindsdb/api/mysql/mysql_proxy/datahub/datahub.py
  mindsdb/api/mysql/mysql_proxy/datahub/datanodes/datasource_datanode.py
  mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py
  mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
  mindsdb/integrations/clickhouse/clickhouse.py
  mindsdb/integrations/mariadb/mariadb.py
  mindsdb/interfaces/datastore/datastore.py
  tests/integration_tests/api/test_http.py
  tests/integration_tests/flows/common.py
  tests/integration_tests/flows/test_clickhouse.py
  tests/integration_tests/flows/test_mariadb.py
Labels: current priority, enhancement

#596 Http modification of config
  .travis.yml
  mindsdb/api/http/initialize.py
  mindsdb/api/http/namespaces/config.py
  mindsdb/api/http/namespaces/configs/config.py
  mindsdb/api/http/start.py
  mindsdb/utilities/config.py
  tests/integration_tests/api/test_http.py
Labels: enhancement, tests

#598 added a few suggestions from Max and modified tests
  mindsdb/api/http/namespaces/config.py
  tests/integration_tests/api/test_http.py
Labels: enhancement

#601 Tests of using FileDS in sql queries
  mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
  mindsdb/api/mysql/mysql_proxy/controllers/session_controller.py
  mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
  tests/docker/mariadb/connect.cnf
  tests/integration_tests/flows/common.py
  tests/integration_tests/flows/test_clickhouse.py
  tests/integration_tests/flows/test_mariadb.py
Labels: bug, tests

#602 table name escaping
  mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
  mindsdb/integrations/clickhouse/clickhouse.py
  mindsdb/integrations/mariadb/mariadb.py
  mindsdb/interfaces/datastore/datastore.py
Labels: bug

#604 Validity check and migrations for Config
  mindsdb/__main__.py
  mindsdb/utilities/config.py
  mindsdb/utilities/wizards.py
  tests/integration_tests/api/test_http.py
  tests/integration_tests/flows/common.py
  tests/integration_tests/flows/config/config.json
Labels: bug, enhancement

#605 make cert if it not specified in config
  mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
Labels: enhancement

#612 fix sql query if table field contains dot
  mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
Labels: bug

#613 fix timestamp transformation
  mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py
Labels: bug
