Repository mindsdb/mindsdb, pull requests merged in 2020-06, with the labels that each got.

#456 Manual (Sub)type setting
  mindsdb/__about__.py
  mindsdb/libs/constants/mindsdb.py
  mindsdb/libs/controllers/predictor.py
  mindsdb/libs/controllers/transaction.py
  mindsdb/libs/data_types/data_source.py
  mindsdb/libs/phases/data_extractor/data_extractor.py
  mindsdb/libs/phases/stats_generator/stats_generator.py
  tests/ci_tests/tests.py
  tests/functional_testing/data_source_setting.py
Labels: enhancement, tests

#468 Various change required to finalize Scout v2
  mindsdb/__about__.py
  mindsdb/libs/backends/lightwood.py
  mindsdb/libs/phases/stats_generator/stats_generator.py
  optional_requirements_ludwig_model.txt
Labels: current priority, dependencies, enhancement

#517 fix #516 flask global objects
  mindsdb/__about__.py
  mindsdb/api/http/initialize.py
  mindsdb/api/http/namespaces/datasource.py
  mindsdb/api/http/namespaces/predictor.py
Labels: bug

#542 fix #540 allow login with empty password
  mindsdb/__about__.py
  mindsdb/api/mysql/mysql_proxy/datahub/datanodes/csv_datanode.py
  mindsdb/api/mysql/mysql_proxy/datahub/datanodes/datanode.py
  mindsdb/api/mysql/mysql_proxy/datahub/datanodes/fake_datanode.py
  mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mongo_datanode.py
  mindsdb/api/mysql/mysql_proxy/datahub/information_schema.py
  mindsdb/api/mysql/mysql_proxy/libs/constants/mysql.py
  mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
Labels: bug, current priority

#545 DB intergrations features
  .gitignore
  mindsdb/__main__.py
  mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py
  mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
  mindsdb/interfaces/clickhouse/clickhouse.py
  mindsdb/interfaces/mariadb/mariadb.py
  mindsdb/interfaces/native/mindsdb.py
  mindsdb/interfaces/native/predictor_process.py
  mindsdb/utilities/config.py
  tests/docker/cli.sh
  tests/docker/docker-compose.yml
  tests/docker/mariadb/Dockerfile
  tests/docker/mariadb/connect.cnf
  tests/home_rentals.csv
  tests/integration_tests/common.py
  tests/integration_tests/test_mariadb.py
Labels: enhancement, tests
