Repository mindsdb/mindsdb, pull requests merged in 2020-10, with the labels that each got.

#748 Added check if python version < 3.6 on server start
  .gitignore
  mindsdb/__main__.py
Labels: hacktoberfest

#745 Added Virtual Environment install instructions
  README.md
  assets/contributions-agreement/signatures/cla.json
Labels: hacktoberfest

#760 Let it snowflake
  .github/workflows/mindsdb.yml
  mindsdb/api/http/namespaces/datasource.py
  mindsdb/interfaces/datastore/datastore.py
Labels: enhancement

#779 change docker cmd to start mindsdb server
  distributions/docker/Dockerfile
Labels: hacktoberfest-accepted

#778 Added correct URL to build-docker.sh
  distributions/docker/build-docker.sh
Labels: hacktoberfest-accepted

#813 Added endpoint for mindsdb version
  mindsdb/api/http/namespaces/util.py
Labels: hacktoberfest-accepted

#816 tell user to run as administrator on PermissionError
  distributions/windows/install.py
Labels: enhancement

#815 fix windows installer
  .github/workflows/mindsdb.yml
Labels: bug

#827 Added delete method to SqlStatementParser
  mindsdb/api/mysql/mysql_proxy/classes/sql_statement_parser.py
Labels: enhancement, hacktoberfest-accepted

#820 Better data sourcing
  INTEGRATION.md
  mindsdb/api/http/namespaces/datasource.py
  mindsdb/api/http/namespaces/predictor.py
  mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
  mindsdb/interfaces/datastore/datastore.py
Labels: enhancement

#833 message after successfull installation (windows installer)
  distributions/windows/install.py
Labels: enhancement

#844 Fixed delete
  mindsdb/interfaces/datastore/datastore.py
Labels: bug

#841 Static file fix(?)
  .gitignore
  mindsdb/api/http/initialize.py
  mindsdb/api/http/start.py
Labels: bug

#858 Caching data analysis forever
  mindsdb/api/http/namespaces/datasource.py
Labels: bug
