Repository mindsdb/mindsdb, pull requests merged in 2020-02, with the labels that each got.

#389 New Explain
  .travis.yml
  mindsdb/__about__.py
  mindsdb/libs/controllers/transaction.py
  mindsdb/libs/data_types/transaction_output_data.py
  mindsdb/libs/data_types/transaction_output_row.py
  mindsdb/libs/helpers/explain_prediction.py
  mindsdb/libs/helpers/general_helpers.py
  requirements.txt
  test.py
  tests/ci_tests/tests.py
Labels: enhancement

#391 Add SageMaker integration docs
  docs/website/docs/AccuracyComparison.md
  docs/website/docs/AwsSageMaker.md
  docs/website/docs/CallSageMakerEndpoint.md
  docs/website/docs/MindsDBSageContainer.md
  docs/website/docs/UseMindsDBinSage.md
  docs/website/docs/assets/mdb-sage-flow.png
  docs/website/website/sidebars.json
  docs/website/website/static/img/mdb-sage-flow.png
Labels: documentation

#392 Travis CI: Find Python syntax errors and undefined names
  .travis.yml
  mindsdb/libs/backends/ludwig.py
  mindsdb/libs/helpers/parser.py
  mindsdb/libs/helpers/probabilistic_validator.py
  mindsdb/libs/phases/stats_generator/stats_generator.py
  mindsdb/scraps.py
Labels: bug

#393 Various Fixes for issues that accumulated
  mindsdb/__about__.py
  mindsdb/libs/backends/lightwood.py
  mindsdb/libs/backends/ludwig.py
  mindsdb/libs/controllers/transaction.py
  mindsdb/libs/helpers/general_helpers.py
  mindsdb/libs/phases/data_extractor/data_extractor.py
  mindsdb/libs/phases/data_transformer/data_transformer.py
  mindsdb/libs/phases/model_analyzer/helpers/column_evaluator.py
  mindsdb/libs/phases/stats_generator/scores.py
  mindsdb/libs/phases/stats_generator/stats_generator.py
  tests/ci_tests/tests.py
  tests/integration_tests/data_generators.py
Labels: bug, refactor
