Repository mindsdb/mindsdb, pull requests merged in 2020-12, with the labels that each got.

#981 Checking connection to DB without creating integration.
  mindsdb/api/http/namespaces/config.py
Labels: enhancement

#1002 run as admin by default
  distributions/windows/build_installers.py
Labels: enhancement

#1000 install pywin32 before winshell to build windows installer
  .github/workflows/mindsdb.yml
  .github/workflows/release.yml
Labels: bug

#973 add icon to windows installer
  .github/workflows/mindsdb.yml
  .github/workflows/release.yml
  distributions/windows/build_installers.py
  distributions/windows/install.py
Labels: enhancement

#1006 Fix actions
  .github/workflows/mindsdb.yml
  .github/workflows/release.yml
  mindsdb/__about__.py
  requirements.txt
Labels: bug, refactor
