Repository mindsdb/mindsdb, pull requests merged in 2023-12, with the labels that each got.

#8459 updated knowledge bases docs
  docs/agents/agent.mdx
Labels: documentation

#8422 updated connection docs for mysql and mariadb
  docs/integrations/data-integrations/mariadb.mdx
  docs/integrations/data-integrations/mysql.mdx
  mindsdb/integrations/handlers/mariadb_handler/README.md
  mindsdb/integrations/handlers/mysql_handler/README.md
Labels: documentation

#8454 Build arm64 docker images
  .github/workflows/docker_build.yml
  docker/docker-bake.hcl
  docker/mindsdb.Dockerfile
  mindsdb/integrations/handlers/chromadb_handler/requirements.txt
  mindsdb/integrations/handlers/rag_handler/requirements.txt
  requirements/requirements.txt
  setup.py
  tests/scripts/check_requirements.py
Labels: deploy-to-alpha-dev

#8469 updated join docs
  docs/sql/api/join.mdx
Labels: documentation

#8526 Add handlers deps to dev
  docker/docker-bake.hcl
Labels: deploy-to-dev
