Repository mindsdb/mindsdb, pull requests merged in 2023-11, with the labels that each got.

#8232 updated shopify docs
  docs/integrations/app-integrations/shopify.mdx
Labels: documentation

#8170 discord app handler
  .flake8
  mindsdb/integrations/handlers/discord_handler/README.md
  mindsdb/integrations/handlers/discord_handler/__about__.py
  mindsdb/integrations/handlers/discord_handler/__init__.py
  mindsdb/integrations/handlers/discord_handler/discord_handler.py
  mindsdb/integrations/handlers/discord_handler/discord_tables.py
  mindsdb/integrations/handlers/discord_handler/icon.png
  mindsdb/integrations/handlers/discord_handler/requirements.txt
  mindsdb/integrations/handlers/discord_handler/tests/__init__.py
  mindsdb/integrations/handlers/discord_handler/tests/test_discord.py
Labels: CalHacks 10.0

#8314 updated twitter chatbot tutorials
  docs/assets/TWbot-response-image.png
  docs/assets/TWbot-response5.png
  docs/sql/tutorials/twitter-chatbot.mdx
  docs/sql/tutorials/twitterbot-mariadb-enterprise-server-skysql.mdx
Labels: documentation

#8367 updated create and drop commands docs
  docs/sql/create/database.mdx
  docs/sql/create/jobs.mdx
  docs/sql/create/ml-engine.mdx
  docs/sql/create/model.mdx
  docs/sql/create/project.mdx
  docs/sql/create/view.mdx
  docs/sql/drop/database.mdx
  docs/sql/drop/jobs.mdx
  docs/sql/drop/ml-engine.mdx
  docs/sql/drop/model.mdx
  docs/sql/drop/project.mdx
  docs/sql/drop/view.mdx
Labels: documentation

#8368 updated mongo docs
  docs/integrations/data-integrations/mongodb.mdx
  docs/mongo/databases/insertOne.mdx
Labels: documentation

#8376 updated docs to direct traffic to open-source
  docs/mint.json
  docs/quickstart.mdx
Labels: documentation

#8378 added twilio chatbot tutorial
  docs/assets/twilio-chatbot-diagram.png
  docs/assets/twilio-chatbot-response.png
  docs/assets/twilio-image-model-image.png
  docs/assets/twilio-image-model-response.png
  docs/assets/twilio-text-model-response.png
  docs/mint.json
  docs/sql/tutorials/twilio-chatbot.mdx
Labels: documentation

#8395 Various requirements tweaks
  mindsdb/integrations/handlers/huggingface_handler/requirements_cpu.txt
  requirements/requirements-grpc.txt
  requirements/requirements.txt
  setup.py
  tests/scripts/check_requirements.py
Labels: deploy-to-alpha-dev

#8401 docs for agents and chatbots
  docs/agents/agent.mdx
  docs/agents/chatbot.mdx
  docs/mint.json
Labels: documentation

#8399 updated mindsdb installation docs
  docs/contribute/install.mdx
  docs/setup/self-hosted/pip/linux.mdx
  docs/setup/self-hosted/pip/macos.mdx
  docs/setup/self-hosted/pip/source.mdx
  docs/setup/self-hosted/pip/windows.mdx
Labels: documentation

#8384 added info about dependencies to installation docs
  docs/contribute/install.mdx
  docs/setup/self-hosted/pip/linux.mdx
  docs/setup/self-hosted/pip/macos.mdx
  docs/setup/self-hosted/pip/source.mdx
  docs/setup/self-hosted/pip/windows.mdx
Labels: documentation

#8295 [fix] optional hierarchical reconciliation
  docker/docker-bake.hcl
  mindsdb/integrations/handlers/neuralforecast_handler/neuralforecast_handler.py
  mindsdb/integrations/handlers/neuralforecast_handler/requirements_extra.txt
  mindsdb/integrations/handlers/statsforecast_handler/requirements_extra.txt
  mindsdb/integrations/handlers/statsforecast_handler/statsforecast_handler.py
  mindsdb/integrations/utilities/time_series_utils.py
  requirements/requirements.txt
  setup.py
  tests/scripts/check_requirements.py
Labels: deploy-to-alpha-dev

#8412 docs updates: chatbots, langchain, slack
  docs/integrations/ai-engines/langchain.mdx
  docs/integrations/app-integrations/slack.mdx
  docs/sql/tutorials/create-chatbot.mdx
Labels: documentation

#8419 updates to ai engines doc pages
  docs/integrations/ai-engines/anthropic.mdx
  docs/integrations/ai-engines/cohere.mdx
  docs/integrations/ai-engines/langchain.mdx
  docs/integrations/ai-engines/openai.mdx
Labels: documentation

#8420 added docs for rag
  docs/integrations/ai-engines/rag.mdx
  docs/integrations/ml-engines-overview.mdx
  docs/mint.json
Labels: documentation
