Repository mindsdb/mindsdb, pull requests merged in 2023-08, with the labels that each got.

#6992 added shopify docs to nav
  docs/app-integrations/shopify.mdx
  docs/mint.json
Labels: documentation

#6998 updated when to use service_account_keys or service_account_json
  docs/data-integrations/google-bigquery.mdx
Labels: documentation

#7042 misc docs updates
  docs/assets/what_is_mindsdb2.png
  docs/connect/mongo-compass.mdx
  docs/connect/mongo-shell.mdx
  docs/integrations/ai-engines/openai.mdx
  docs/integrations/data-integrations/oracle.mdx
  docs/sql/create/ml-engine.mdx
  docs/what-is-mindsdb.mdx
Labels: documentation

#7052 improve youtube documentation
  mindsdb/integrations/handlers/youtube_handler/youtube_handler.py
Labels: bug, documentation

#7046 updated a query
  docs/what-is-mindsdb.mdx
Labels: documentation

#7047 removed temp python sdk file
  docs/temp-python-sdk.mdx
Labels: documentation

#7068 twitter tutorial fix
  docs/assets/tutorials/twitter_chatbot/placeholder.png
  docs/sql/tutorials/twitterbot-mariadb-enterprise-server-skysql.mdx
Labels: documentation

#7083 added author link to twitter tutorial
  docs/sql/tutorials/twitterbot-mariadb-enterprise-server-skysql.mdx
Labels: documentation

#7079 fixed image in slack tutorial
  docs/sql/tutorials/slack-chatbot.mdx
Labels: documentation

#7078 fixed links
  docs/data_sources.mdx
  docs/ml_engines.mdx
  docs/sql/project.mdx
Labels: documentation

#7119 docs for web crawler
  docs/integrations/app-integrations/web-crawler.mdx
  docs/mint.json
Labels: documentation

#7125 added email docs
  docs/integrations/app-integrations/binance.mdx
  docs/integrations/app-integrations/confluence.mdx
  docs/integrations/app-integrations/email.mdx
  docs/integrations/app-integrations/plaid.mdx
  docs/integrations/app-integrations/reddit.mdx
  docs/integrations/app-integrations/shopify.mdx
  docs/integrations/data-sources-overview.mdx
  docs/mint.json
Labels: documentation

#7128 added docs for llm ui and slack
  docs/assets/tutorials/llm-chatbot-ui/chat.png
  docs/assets/tutorials/llm-chatbot-ui/prompt.png
  docs/assets/tutorials/llm-chatbot-ui/publish.png
  docs/assets/tutorials/llm-chatbot-ui/settings.png
  docs/assets/tutorials/llm-chatbot-ui/settings2.png
  docs/assets/tutorials/llm-chatbot-ui/slack.png
  docs/assets/tutorials/llm-chatbot-ui/welcome.png
  docs/integrations/app-integrations/slack.mdx
  docs/integrations/data-sources-overview.mdx
  docs/mint.json
  docs/sql/tutorials/llm-chatbot-ui.mdx
Labels: documentation

#7124 added an faq page
  docs/faqs/mindsdb-with-php.mdx
  docs/mint.json
Labels: documentation

#7134 Fix clickhouse documentation
  mindsdb/integrations/handlers/clickhouse_handler/clickhouse_handler.py
Labels: bug

#7135 Update Ignite documentation
  mindsdb/integrations/handlers/ignite_handler/ignite_handler.py
Labels: documentation

#7051 Improve Github Documentation
  mindsdb/integrations/handlers/github_handler/__init__.py
  mindsdb/integrations/handlers/github_handler/github_handler.py
Labels: enhancement, documentation

#7192 updated slack docs with permissions
  docs/integrations/app-integrations/slack.mdx
  docs/sql/tutorials/slack-chatbot.mdx
Labels: documentation

#7194 updated git clone
  docs/contribute/install.mdx
Labels: documentation

#7179 Update documentation on Scylla dna Cassandra
  mindsdb/integrations/handlers/cassandra_handler/cassandra_handler.py
  mindsdb/integrations/handlers/scylla_handler/scylla_handler.py
Labels: documentation

#7201 Defensive coding for None connection_args
  mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py
  mindsdb/interfaces/database/integrations.py
Labels: bug

#7199 added json_extract() to docs
  docs/nlp/json-from-text.mdx
Labels: documentation

#7200 complete surrealDB documentation
  mindsdb/integrations/handlers/surrealdb_handler/surrealdb_handler.py
Labels: documentation

#7206 added quickstart video
  docs/quickstart.mdx
Labels: documentation
