Repository mindsdb/mindsdb, pull requests merged in 2024-05, with the labels that each got.

#9154 removed ref to mindsdb (cloud) pro
  docs/integrations/ai-engines/byom.mdx
  docs/mindsdb-gui.mdx
  docs/sdks/javascript/connect.mdx
  docs/sdks/mongo/connect/mongo-compass.mdx
  docs/sdks/mongo/connect/mongo-shell.mdx
  docs/sdks/python/connect.mdx
Labels: documentation

#9167 updated use cases diagrams
  docs/assets/use_cases/ai_agents.jpg
  docs/assets/use_cases/ai_agents.png
  docs/assets/use_cases/ai_workflow_automation.jpg
  docs/assets/use_cases/ai_workflow_automation.png
  docs/assets/use_cases/aipowered_data_retrieval.jpg
  docs/assets/use_cases/aipowered_data_retrieval.png
  docs/assets/use_cases/automated_finetuning.jpg
  docs/assets/use_cases/automated_finetuning.png
  docs/assets/use_cases/data_enrichment.jpg
  docs/assets/use_cases/data_enrichment.png
  docs/assets/use_cases/indatabase_ml.jpg
  docs/assets/use_cases/indatabase_ml.png
  docs/assets/use_cases/predictive_analytics.jpg
  docs/assets/use_cases/predictive_analytics.png
  docs/use-cases/ai-powered_data_retrieval/overview.mdx
  docs/use-cases/ai_agents/overview.mdx
  docs/use-cases/ai_workflow_automation/overview.mdx
  docs/use-cases/automated_finetuning/overview.mdx
  docs/use-cases/data_enrichment/overview.mdx
  docs/use-cases/in-database_ml/overview.mdx
  docs/use-cases/predictive_analytics/overview.mdx
Labels: documentation

#9152 Anomaly detection docs
  docs/integrations/ai-engines/anomaly.mdx
  docs/mint.json
  docs/use-cases/predictive_analytics/overview.mdx
  mindsdb/integrations/handlers/anomaly_detection_handler/README.md
Labels: documentation

#9165 remove references to removed table
  .github/workflows/matrix_includes.json
  default_handlers.txt
  docs/integrations/ai-engines/openai.mdx
  docs/mindsdb_sql/connect/jupysql.mdx
  docs/mindsdb_sql/sql/api/finetune.mdx
  docs/mindsdb_sql/sql/api/manage-models-versions.mdx
  docs/mindsdb_sql/sql/api/retrain.mdx
  docs/mindsdb_sql/sql/show-models.mdx
  docs/sdks/mongo/collection-structure.mdx
  docs/sdks/mongo/models/find.mdx
  docs/sql/project.mdx
  docs/sql/table-structure.mdx
  docs/use-cases/automated_finetuning/anyscale.mdx
  docs/use-cases/automated_finetuning/classification.mdx
  docs/use-cases/automated_finetuning/openai.mdx
  docs/use-cases/automated_finetuning/regression.mdx
  mindsdb/api/executor/datahub/datanodes/project_datanode.py
  mindsdb/api/executor/utilities/sql.py
  mindsdb/api/mongo/responders/delete.py
  mindsdb/api/mongo/responders/find.py
  mindsdb/integrations/handlers/file_handler/__init__.py
  mindsdb/integrations/handlers/langchain_embedding_handler/langchain_embedding_handler.py
  mindsdb/integrations/handlers/langchain_embedding_handler/requirements.txt
  mindsdb/integrations/handlers/langchain_handler/requirements.txt
  mindsdb/integrations/handlers/mysql_handler/mysql_handler.py
  mindsdb/integrations/handlers/openai_handler/requirements.txt
  tests/api/http/tables_test.py
  tests/handler_tests/test_mariadb_handler.py
  tests/integration_tests/flows/test_company_independent.py
  tests/integration_tests/flows/test_http.py
  tests/integration_tests/flows/test_mysql_api.py
  tests/unit/handlers/test_mysql.py
  tests/unit/test_mongodb_server.py
Labels: deploy-to-dev

#9120 Fix mysql connection status tracking
  .dockerignore
  .github/workflows/test_on_deploy.yml
  default_handlers.txt
  docs/integrations/ai-engines/anomaly.mdx
  mindsdb/integrations/handlers/mysql_handler/mysql_handler.py
Labels: deploy-to-dev

#9091 Restrict concurrent gha workflows
  .github/workflows/build_deploy_dev.yml
  .github/workflows/build_deploy_prod.yml
  .github/workflows/build_deploy_staging.yml
  .github/workflows/test_on_push.yml
Labels: deploy-to-alpha-dev

#9170 Bump type_infer to 0.0.20
  mindsdb/integrations/handlers/autogluon_handler/requirements.txt
  mindsdb/integrations/handlers/autosklearn_handler/requirements.txt
  mindsdb/integrations/handlers/flaml_handler/requirements.txt
  mindsdb/integrations/handlers/lightwood_handler/requirements.txt
  mindsdb/integrations/handlers/tpot_handler/requirements.txt
Labels: deploy-to-alpha-dev

#9121 Update pydantic to 2.0
  mindsdb/integrations/handlers/timegpt_handler/README.md
  mindsdb/integrations/handlers/timegpt_handler/requirements.txt
  mindsdb/integrations/handlers/timegpt_handler/timegpt_handler.py
  requirements/requirements.txt
Labels: deploy-to-dev

#9175 updated handler link
  docs/integrations/ai-engines/mindsdb_inference.mdx
Labels: documentation

#9168 python sdk docs for agents and jobs
  docs/mint.json
  docs/sdks/python/agents.mdx
  docs/sdks/python/agents_knowledge_bases.mdx
  docs/sdks/python/agents_skills.mdx
  docs/sdks/python/create_database.mdx
  docs/sdks/python/create_job.mdx
  docs/sdks/python/create_model.mdx
  docs/sdks/python/create_project.mdx
  docs/sdks/python/create_table.mdx
  docs/sdks/python/create_view.mdx
  docs/sdks/python/describe.mdx
  docs/sdks/python/drop_database.mdx
  docs/sdks/python/drop_job.mdx
  docs/sdks/python/drop_model.mdx
  docs/sdks/python/drop_project.mdx
  docs/sdks/python/drop_view.mdx
  docs/sdks/python/finetune.mdx
  docs/sdks/python/get-batch-predictions.mdx
  docs/sdks/python/get-single-prediction.mdx
  docs/sdks/python/get_history.mdx
  docs/sdks/python/get_status.mdx
  docs/sdks/python/list_databases.mdx
  docs/sdks/python/list_jobs.mdx
  docs/sdks/python/list_models.mdx
  docs/sdks/python/list_projects.mdx
  docs/sdks/python/list_views.mdx
  docs/sdks/python/manage-model-versions.mdx
  docs/sdks/python/query_projects.mdx
  docs/sdks/python/query_table.mdx
  docs/sdks/python/query_view.mdx
  docs/sdks/python/refresh_job.mdx
  docs/sdks/python/refresh_model.mdx
  docs/sdks/python/retrain.mdx
Labels: documentation

#9183 updated mongo syntax
  docs/integrations/ai-engines/statsforecast.mdx
  docs/use-cases/data_enrichment/question-answering-inside-mongodb-with-openai.mdx
  docs/use-cases/data_enrichment/sentiment-analysis-inside-mongodb-with-openai.mdx
  docs/use-cases/data_enrichment/text-summarization-inside-mongodb-with-openai.mdx
Labels: documentation

#9184 removing agents from python sdk docs
  docs/mint.json
Labels: documentation

#9186 Fix pydantic warnings
  .github/workflows/test_on_push.yml
  mindsdb/integrations/handlers/litellm_handler/settings.py
  mindsdb/integrations/handlers/mindsdb_inference/settings.py
  mindsdb/integrations/handlers/ms_teams_handler/settings.py
  mindsdb/integrations/handlers/mysql_handler/settings.py
  mindsdb/integrations/handlers/twelve_labs_handler/settings.py
  mindsdb/integrations/libs/llm/config.py
  mindsdb/integrations/libs/llm/utils.py
  requirements/requirements.txt
Labels: deploy-to-dev

#9194 Improve caching of docker builds
  docker/mindsdb.Dockerfile
Labels: deploy-to-dev

#9200 updates to sql api docs
  docs/mindsdb_sql/sql/api/finetune.mdx
  docs/mindsdb_sql/sql/api/join.mdx
  docs/mindsdb_sql/sql/api/retrain.mdx
  docs/mindsdb_sql/sql/create/jobs.mdx
  docs/mindsdb_sql/sql/create/model.mdx
  docs/sdks/python/agents.mdx
Labels: documentation

#9201 removed rest api for agents
  docs/mint.json
Labels: documentation

#9193 Pydantic V2 migration
  mindsdb/integrations/handlers/chromadb_handler/settings.py
  mindsdb/integrations/handlers/email_handler/settings.py
  mindsdb/integrations/handlers/langchain_handler/langchain_handler.py
  mindsdb/integrations/handlers/lightfm_handler/lightfm_handler.py
  mindsdb/integrations/handlers/litellm_handler/litellm_handler.py
  mindsdb/integrations/handlers/mysql_handler/mysql_handler.py
  mindsdb/integrations/handlers/mysql_handler/settings.py
  mindsdb/integrations/handlers/palm_handler/palm_handler.py
  mindsdb/integrations/handlers/rag_handler/rag.py
  mindsdb/integrations/handlers/rag_handler/settings.py
  mindsdb/integrations/handlers/sentence_transformers_handler/sentence_transformers_handler.py
  mindsdb/integrations/handlers/twelve_labs_handler/settings.py
  mindsdb/integrations/handlers/utilities/validation_utilities/parameter_validation_utilities.py
  mindsdb/integrations/handlers/writer_handler/rag.py
  mindsdb/integrations/handlers/writer_handler/settings.py
  mindsdb/integrations/handlers/writer_handler/writer_handler.py
  mindsdb/integrations/utilities/rag/settings.py
Labels: deploy-to-dev

#9207 updated automated finetuning tutorials
  docs/use-cases/automated_finetuning/anyscale.mdx
  docs/use-cases/automated_finetuning/classification.mdx
  docs/use-cases/automated_finetuning/openai.mdx
  docs/use-cases/automated_finetuning/regression.mdx
Labels: documentation

#9204 enhanced user journey through docs
  docs/features/ai-integrations.mdx
  docs/features/data-integrations.mdx
  docs/features/model-management.mdx
  docs/integrations/ai-engines/replicate-audio.mdx
  docs/integrations/ai-engines/replicate-img2text.mdx
  docs/integrations/ai-engines/replicate-llm.mdx
  docs/integrations/ai-engines/replicate-text2img.mdx
  docs/integrations/ai-engines/replicate-text2video.mdx
  docs/integrations/ai-engines/twelvelabs.mdx
  docs/integrations/ai-overview.mdx
  docs/integrations/data-overview.mdx
  docs/integrations/integrations.mdx
  docs/mindsdb_sql/overview.mdx
  docs/mint.json
  docs/rest/overview.mdx
  docs/sdks/overview.mdx
  docs/use-cases/ai-powered_data_retrieval/overview.mdx
  docs/use-cases/ai_agents/overview.mdx
  docs/use-cases/ai_workflow_automation/overview.mdx
  docs/use-cases/automated_finetuning/overview.mdx
  docs/use-cases/data_enrichment/overview.mdx
  docs/use-cases/in-database_ml/overview.mdx
  docs/use-cases/predictive_analytics/overview.mdx
  docs/what-is-mindsdb.mdx
Labels: documentation

#9214 updated mql tutorials
  docs/use-cases/data_enrichment/question-answering-inside-mongodb-with-openai.mdx
  docs/use-cases/data_enrichment/sentiment-analysis-inside-mongodb-with-openai.mdx
  docs/use-cases/data_enrichment/text-summarization-inside-mongodb-with-openai.mdx
Labels: documentation

#9212 bump lightwood version
  mindsdb/integrations/handlers/lightwood_handler/requirements.txt
  requirements/requirements-test.txt
  requirements/requirements.txt
Labels: deploy-to-dev

#9219 updated trigger docs
  docs/mindsdb_sql/sql/create/trigger.mdx
Labels: documentation

#9248 Update references to sample databases
  docs/integrations/ai-engines/lightfm.mdx
  docs/integrations/ai-engines/neuralforecast.mdx
  docs/integrations/ai-engines/popularity-recommender.mdx
  docs/integrations/ai-engines/rag.mdx
  docs/integrations/ai-engines/statsforecast.mdx
  docs/mindsdb_sql/connect/grafana.mdx
  docs/quickstart-tutorial.mdx
  docs/sdks/javascript/create_database.mdx
  docs/sdks/python/create_database.mdx
  docs/use-cases/ai-powered_data_retrieval/semantic_search.mdx
  docs/use-cases/data_enrichment/question-answering-inside-mysql-with-openai.mdx
  docs/use-cases/data_enrichment/sentiment-analysis-inside-mysql-with-openai.mdx
  docs/use-cases/data_enrichment/text-summarization-inside-mysql-with-openai.mdx
  docs/use-cases/predictive_analytics/expenditures-statsforecast.mdx
  docs/use-cases/predictive_analytics/house-sales-statsforecast.mdx
  docs/use-cases/predictive_analytics/house-sales-timegpt.mdx
  docs/use-cases/predictive_analytics/monthly-expediture-timegpt.mdx
  mindsdb/integrations/handlers/langchain_embedding_handler/README.md
  mindsdb/integrations/handlers/rag_handler/README.md
  mindsdb/integrations/handlers/spacy_handler/README.md
  tests/integration_tests/flows/test_predict_text_sentiment_openai_tutorial.py
Labels: deploy-to-dev

#9258 updated mongodb sdk to api
  docs/mint.json
Labels: documentation
