Repository mindsdb/mindsdb, pull requests merged in 2024-02, with the labels that each got.

#8711 Move lanchain skills to langchain handler.
  mindsdb/integrations/handlers/file_handler/requirements.txt
  mindsdb/integrations/handlers/langchain_embedding_handler/requirements.txt
  mindsdb/integrations/handlers/langchain_handler/requirements.txt
  mindsdb/integrations/handlers/langchain_handler/skill_tool.py
  mindsdb/integrations/handlers/langchain_handler/tools.py
  mindsdb/integrations/handlers/rag_handler/requirements.txt
  mindsdb/integrations/handlers/writer_handler/requirements.txt
  requirements/requirements.txt
  setup.py
  tests/scripts/check_requirements.py
Labels: deploy-to-alpha-dev

#8740 updates to postgres docs
  docs/integrations/data-integrations/postgresql.mdx
Labels: documentation

#8741 youtube docs
  docs/integrations/app-integrations/youtube.mdx
Labels: documentation

#8744 youtube docs for connecting
  docs/integrations/app-integrations/youtube.mdx
Labels: documentation

#8755 updated deprecated openai models
  docs/finetune/openai.mdx
  docs/integrations/ai-engines/openai.mdx
  docs/nlp/nlp-mindsdb-openai.mdx
Labels: documentation

#8756 sql api updates
  docs/mindsdb_sql/sql/create/jobs.mdx
  docs/mindsdb_sql/sql/create/model.mdx
Labels: documentation

#7336 updated neuralforecast parameters in docs
  docs/integrations/ai-engines/neuralforecast.mdx
Labels: documentation

#8770 updated mindsdb intro
  docs/what-is-mindsdb.mdx
Labels: documentation

#8767 Add couchbase to cloud docker image
  docker/docker-bake.hcl
Labels: deploy-to-alpha-dev

#8750 Update twitter-chatbot.mdx to use LAST
  docs/sql/tutorials/twitter-chatbot.mdx
Labels: documentation

#8772 updated slack chatbot tutorial
  docs/sql/tutorials/slack-chatbot.mdx
Labels: documentation

#8775 updated intro docs
  docs/mint.json
  docs/what-is-mindsdb.mdx
Labels: documentation

#8776 updated last keyword docs
  docs/mindsdb_sql/sql/create/jobs.mdx
Labels: documentation

#8779 added anyscale docs
  docs/integrations/ai-engines/anyscale.mdx
  docs/mint.json
  docs/sdks/javascript/overview.mdx
  docs/sdks/mongo/mindsdb-mongo-ql-overview.mdx
  docs/sdks/python/overview.mdx
Labels: documentation

#8780 rag param update in docs
  docs/integrations/ai-engines/rag.mdx
Labels: documentation

#8804 Add 12labs handler to cloud
  docker/docker-bake.hcl
Labels: deploy-to-dev

#8809 fixed api_key param names
  docs/finetune/openai.mdx
  docs/integrations/ai-engines/huggingface_inference_api.mdx
  docs/integrations/ai-engines/timegpt.mdx
  docs/integrations/ai-engines/twelvelabs.mdx
  docs/mindsdb_sql/agents/agent.mdx
  docs/mindsdb_sql/agents/knowledge-bases.mdx
  docs/sdks/python/create_ml_engine.mdx
  docs/sql/tutorials/create-chatbot-kb.mdx
  docs/sql/tutorials/create-chatbot.mdx
  docs/sql/tutorials/twitter-chatbot.mdx
Labels: documentation

#8808 added info to finetune commands
  docs/finetune/anyscale.mdx
  docs/finetune/classification.mdx
  docs/finetune/openai.mdx
  docs/finetune/regression.mdx
  docs/mindsdb_sql/sql/api/finetune.mdx
Labels: documentation

#8763 Refactor docker bake file
  .dockerignore
  .github/actions/docker-bake/action.yml
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-staging.yml
  .github/workflows/release.yml
  docker/docker-bake.hcl
  docker/mindsdb.Dockerfile
Labels: deploy-to-alpha-dev

#8810 update to rest api docs
  docs/mint.json
  docs/rest/models/query-model-joined-with-data.mdx
Labels: documentation

#8811 docs rearranged and modified intro pages
  docs/automation.mdx
  docs/data_sources.mdx
  docs/generative-ai-tables.mdx
  docs/integrations/ai-overview.mdx
  docs/integrations/data-overview.mdx
  docs/mint.json
  docs/quickstart-tutorial.mdx
  docs/sdks/mongo/delete.mdx
  docs/sdks/mongo/insert.mdx
  docs/sdks/mongo/models/deleteOne.mdx
  docs/sdks/mongo/models/find.mdx
  docs/sdks/mongo/models/insertOne.mdx
  docs/sql/api/finetune.mdx
  docs/sql/create/database.mdx
  docs/sql/create/file.mdx
  docs/sql/create/jobs.mdx
  docs/sql/create/trigger.mdx
  docs/sql/create/view.mdx
  docs/sql/tutorials/customer-reviews-notifications.mdx
  docs/sql/tutorials/real-time-trading-forecasts.mdx
Labels: documentation

#8832 added a note that create table needs database with write access
  docs/mindsdb_sql/sql/create/table.mdx
Labels: documentation

#8835 added eeg forecast tutorial
  docs/sql/tutorials/eeg-forecasting.mdx
Labels: documentation

#8840 fixed query in tutorial
  docs/finetune/anyscale.mdx
Labels: documentation

#8845 updated tutorials for learning hub
  docs/mint.json
  docs/sql/tutorials/expenditures-statsforecast.mdx
  docs/sql/tutorials/home-rentals.mdx
  docs/sql/tutorials/house-sales-forecasting.mdx
  docs/sql/tutorials/text-sentiment-hf.mdx
  docs/sql/tutorials/twitter-chatbot.mdx
Labels: documentation
