Repository mindsdb/mindsdb, pull requests merged in 2024-04, with the labels that each got.

#9025 updated hostname of sample dbs
  docs/callbacks.mdx
  docs/finetune/anyscale.mdx
  docs/finetune/data.csv
  docs/finetune/regression.mdx
  docs/getting-started.mdx
  docs/integrations/ai-engines/openai.mdx
  docs/mindsdb_sql/agents/agent.mdx
  docs/mindsdb_sql/connect/metabase.mdx
  docs/mindsdb_sql/sql/native-queries.mdx
  docs/nlp/nlp-mindsdb-openai.mdx
  docs/quickstart.mdx
  docs/sql/feature-eng.mdx
  docs/sql/tutorials/customer-churn.mdx
  docs/sql/tutorials/eeg-forecasting.mdx
  docs/sql/tutorials/home-rentals.mdx
  docs/sql/tutorials/house-sales-forecasting.mdx
  docs/sql/tutorials/text-sentiment-hf.mdx
  mindsdb/README.md
  mindsdb/integrations/handlers/hsqldb_handler/README.md
Labels: documentation

#9026 fixed slack chatbot tutorial
  docs/sql/tutorials/slack-chatbot.mdx
Labels: documentation

#9035 updated email integration docs
  docs/integrations/app-integrations/email.mdx
Labels: documentation

#8995 updated ollama docs
  docs/integrations/ai-engines/ollama.mdx
  mindsdb/integrations/handlers/ollama_handler/README.md
Labels: documentation

#8996 Add RAG model and utilities for Mindsdb integration
  mindsdb/integrations/handlers/file_handler/requirements.txt
  mindsdb/integrations/handlers/langchain_handler/log_callback_handler.py
  mindsdb/integrations/handlers/langchain_handler/requirements.txt
  mindsdb/integrations/handlers/rag_handler/requirements.txt
  mindsdb/integrations/handlers/writer_handler/requirements.txt
  mindsdb/integrations/utilities/rag/__init__.py
  mindsdb/integrations/utilities/rag/loaders/__init__.py
  mindsdb/integrations/utilities/rag/loaders/vector_store_loader/__init__.py
  mindsdb/integrations/utilities/rag/loaders/vector_store_loader/vector_store_loader.py
  mindsdb/integrations/utilities/rag/pipelines/__init__.py
  mindsdb/integrations/utilities/rag/pipelines/rag.py
  mindsdb/integrations/utilities/rag/rag_pipeline_builder.py
  mindsdb/integrations/utilities/rag/retrievers/__init__.py
  mindsdb/integrations/utilities/rag/retrievers/auto_retriever.py
  mindsdb/integrations/utilities/rag/retrievers/base.py
  mindsdb/integrations/utilities/rag/retrievers/multi_vector_retriever.py
  mindsdb/integrations/utilities/rag/settings.py
  mindsdb/integrations/utilities/rag/utils.py
  mindsdb/integrations/utilities/rag/vector_store.py
  requirements/requirements.txt
  tests/handler_tests/data/rag_pipelines/auto_retriever.yml
  tests/handler_tests/data/rag_pipelines/multi_retriever_both.yml
  tests/handler_tests/data/rag_pipelines/multi_retriever_split.yml
  tests/handler_tests/data/rag_pipelines/multi_retriever_summarize.yml
  tests/handler_tests/data/rag_pipelines/vector_retriever_chroma.yml
  tests/handler_tests/data/rag_pipelines/vector_retriever_pgvector.yml
  tests/handler_tests/test_rag_pipelines.py
  tests/scripts/check_requirements.py
Labels: enhancement

#9058 updated agents docs
  docs/assets/agent_diagram.png
  docs/assets/chatbot_diagram.png
  docs/mindsdb_sql/agents/agent.mdx
  docs/mindsdb_sql/agents/chatbot.mdx
Labels: documentation

#9059 updated broken links in mongo docs
  docs/integrations/data-integrations/mongodb.mdx
Labels: documentation

#9072 Remove custom GH actions and use shared ones
  .github/actions/docker-bake-cache/action.yml
  .github/actions/docker-bake/action.yml
  .github/workflows/build_deploy_dev.yml
  .github/workflows/build_deploy_prod.yml
  .github/workflows/build_deploy_staging.yml
  .github/workflows/test_on_deploy.yml
  .github/workflows/test_on_push.yml
Labels: deploy-to-alpha-dev

#9082 updated agent skills in docs
  docs/mindsdb_sql/agents/agent.mdx
  docs/sql/tutorials/create-chatbot.mdx
Labels: documentation

#9085 Switch to new GHA runners
  .github/workflows/build_deploy_dev.yml
  .github/workflows/build_deploy_prod.yml
  .github/workflows/build_deploy_staging.yml
Labels: deploy-to-alpha-dev

#9102 mysql and postgres docs + readme updates
  docs/integrations/data-integrations/mysql.mdx
  docs/integrations/data-integrations/postgresql.mdx
  mindsdb/integrations/handlers/mysql_handler/README.md
  mindsdb/integrations/handlers/postgres_handler/README.md
Labels: documentation

#9112 docs cleanup
  docs/contribute/data-integration-page.mdx
  docs/data_sources.mdx
  docs/getting-started.mdx
  docs/mindsdb-sql-overview.mdx
  docs/mindsdb_sql/connect/dbt.mdx
  docs/mint.json
  docs/ml-types.mdx
  docs/ml_engines.mdx
  docs/nlp/nlp-extended-examples.mdx
  docs/nlp/nlp-mindsdb-hf.mdx
  docs/nlp/nlp-mindsdb-openai.mdx
  docs/nlp/what-is-nlp.mdx
  docs/quickstart.mdx
  docs/setup/aws.mdx
  docs/setup/civo.mdx
  docs/setup/cloud-pro.mdx
  docs/setup/cloud-starter.mdx
  docs/setup/cloud.mdx
  docs/setup/digital-ocean.mdx
  docs/setup/gcp.mdx
  docs/setup/vultr.mdx
  docs/sql/project.mdx
  docs/tables_views_files.mdx
  docs/tutorials_mindsdb_no_sql.mdx
  docs/tutorials_mindsdb_sql.mdx
  docs/use-cases/ai_workflow_automation/ai_workflow.mdx
  docs/use-cases/ai_workflow_automation/overview.mdx
  docs/using-mongo-api/classification.mdx
  docs/using-mongo-api/nlp.mdx
  docs/using-mongo-api/regression.mdx
  docs/using-mongo-api/timeseries.mdx
Labels: documentation

#9114 add bigquery to cloud image
  docker/docker-bake.hcl
Labels: deploy-to-demo

#9116 updated triggers docs
  docs/mindsdb_sql/sql/create/trigger.mdx
  docs/mindsdb_sql/sql/drop/trigger.mdx
  docs/mindsdb_sql/sql/query-triggers.mdx
Labels: documentation

#9113 openapi docs for agents/skills/chatbots
  docs/mint.json
  docs/openapi.yml
  docs/rest/agents/agent.mdx
  docs/rest/agents/chatbot.mdx
  docs/rest/agents/create-agent.mdx
  docs/rest/agents/create-chatbot.mdx
  docs/rest/agents/create-skill.mdx
  docs/rest/agents/delete-agent.mdx
  docs/rest/agents/delete-chatbot.mdx
  docs/rest/agents/delete-skill.mdx
  docs/rest/agents/get-agent.mdx
  docs/rest/agents/get-chatbot.mdx
  docs/rest/agents/get-skill.mdx
  docs/rest/agents/list-agents.mdx
  docs/rest/agents/list-chatbots.mdx
  docs/rest/agents/list-skills.mdx
  docs/rest/agents/query-agent.mdx
  docs/rest/agents/update-agent.mdx
  docs/rest/agents/update-chatbot.mdx
  docs/rest/agents/update-skill.mdx
Labels: documentation

#9110 updated use cases docs
  docs/assets/use_cases/ai_agents.png
  docs/assets/use_cases/ai_workflow_automation.png
  docs/assets/use_cases/aipowered_data_retrieval.png
  docs/assets/use_cases/automated_finetuning.png
  docs/assets/use_cases/data_enrichment.png
  docs/assets/use_cases/indatabase_ml.png
  docs/assets/use_cases/predictive_analytics.png
  docs/use-cases/ai-powered_data_retrieval/overview.mdx
  docs/use-cases/ai_agents/overview.mdx
  docs/use-cases/ai_workflow_automation/overview.mdx
  docs/use-cases/automated_finetuning/overview.mdx
  docs/use-cases/data_enrichment/overview.mdx
  docs/use-cases/in-database_ml/overview.mdx
  docs/use-cases/predictive_analytics/overview.mdx
Labels: documentation

#9150 updated docs links in completed readmes&docs for integrations
  docs/integrations/ai-engines/anthropic.mdx
  docs/integrations/ai-engines/anyscale.mdx
  docs/integrations/ai-engines/cohere.mdx
  docs/integrations/ai-engines/huggingface.mdx
  docs/integrations/ai-engines/huggingface_inference_api.mdx
  docs/integrations/ai-engines/langchain.mdx
  docs/integrations/ai-engines/mindsdb_inference.mdx
  docs/integrations/ai-engines/ollama.mdx
  docs/integrations/ai-engines/rag.mdx
  docs/integrations/data-integrations/mysql.mdx
  docs/integrations/data-integrations/postgresql.mdx
  mindsdb/integrations/handlers/anthropic_handler/README.md
  mindsdb/integrations/handlers/anyscale_endpoints_handler/README.md
  mindsdb/integrations/handlers/cohere_handler/README.md
  mindsdb/integrations/handlers/huggingface_api_handler/README.md
  mindsdb/integrations/handlers/huggingface_handler/README.md
  mindsdb/integrations/handlers/langchain_handler/README.md
  mindsdb/integrations/handlers/mindsdb_inference/README.md
  mindsdb/integrations/handlers/mysql_handler/README.md
  mindsdb/integrations/handlers/ollama_handler/README.md
  mindsdb/integrations/handlers/postgres_handler/README.md
  mindsdb/integrations/handlers/rag_handler/README.md
Labels: documentation

#9156 updated a link in openai finetuning tutorial
  docs/use-cases/automated_finetuning/openai.mdx
Labels: documentation
