Repository mindsdb/mindsdb, pull requests merged in 2024-01, with the labels that each got.

#8573 Release v23.12.4.2
  mindsdb/__about__.py
  mindsdb/integrations/handlers/anyscale_endpoints_handler/anyscale_endpoints_handler.py
  mindsdb/integrations/handlers/anyscale_endpoints_handler/requirements.txt
  mindsdb/integrations/handlers/instatus_handler/README.md
  mindsdb/integrations/handlers/instatus_handler/instatus_handler.py
  mindsdb/integrations/handlers/instatus_handler/instatus_tables.py
  mindsdb/integrations/handlers/langchain_embedding_handler/requirements.txt
  mindsdb/integrations/handlers/langchain_handler/langchain_handler.py
  mindsdb/integrations/handlers/langchain_handler/requirements.txt
  mindsdb/integrations/handlers/llama_index_handler/README.md
  mindsdb/integrations/handlers/llama_index_handler/__about__.py
  mindsdb/integrations/handlers/llama_index_handler/__init__.py
  mindsdb/integrations/handlers/llama_index_handler/config.py
  mindsdb/integrations/handlers/llama_index_handler/github_loader_helper.py
  mindsdb/integrations/handlers/llama_index_handler/llama_index_handler.py
  mindsdb/integrations/handlers/llama_index_handler/requirements.txt
  mindsdb/integrations/handlers/openai_handler/constants.py
  mindsdb/integrations/handlers/openai_handler/helpers.py
  mindsdb/integrations/handlers/openai_handler/openai_handler.py
  mindsdb/integrations/handlers/openai_handler/requirements.txt
  mindsdb/integrations/handlers/rag_handler/requirements.txt
  mindsdb/integrations/handlers/rag_handler/settings.py
  tests/handler_tests/test_instatus_handler.py
  tests/unit/ml_handlers/test_langchain_embedding.py
  tests/unit/ml_handlers/test_openai.py
Labels: deploy-to-dev

#8580 fixed tab content in docs
  docs/mint.json
  docs/sql/tutorials/rag.mdx
Labels: documentation

#8596 updated timegpt docs
  docs/integrations/ai-engines/timegpt.mdx
Labels: documentation

#8589 fix issue with pdf upload in cloud
  mindsdb/integrations/handlers/file_handler/file_handler.py
  mindsdb/integrations/handlers/file_handler/requirements.txt
Labels: deploy-to-dev

#8605 Fix neuralforecast and statsforecast in cloud image
  docker/docker-bake.hcl
Labels: deploy-to-alpha-dev

#8615 added info about which slack connection method to use with the chatbot syntax
  docs/agents/chatbot.mdx
  docs/integrations/app-integrations/slack.mdx
Labels: documentation

#8617 linked finetuning blog post
  docs/finetune/anyscale.mdx
Labels: documentation

#8618 updated syntax of describe, retrain, finetune
  docs/sql/api/describe.mdx
  docs/sql/api/finetune.mdx
  docs/sql/api/retrain.mdx
Labels: documentation

#8609 More deploy triggers and simplify docker
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-staging.yml
  .github/workflows/release.yml
  docker/docker-bake.hcl
Labels: deploy-to-precise-dev

#8612 fix drop table for vectordatabase_handler.py and specifically chroma
  mindsdb/integrations/handlers/chromadb_handler/chromadb_handler.py
  mindsdb/integrations/handlers/chromadb_handler/tests/test_chromadb_handler.py
  mindsdb/integrations/libs/vectordatabase_handler.py
Labels: deploy-to-dev

#8656 updated agent/chatbot tutorial
  docs/sql/tutorials/create-chatbot.mdx
Labels: documentation

#8655 removed chatbot ui docs
  docs/mint.json
Labels: documentation

#8657 updated timegpt docs with more info
  docs/integrations/ai-engines/timegpt.mdx
Labels: documentation

#8652 Added dependencies to k8s, LLM fixes
  docker/docker-bake.hcl
  mindsdb/integrations/handlers/llama_index_handler/README.md
  mindsdb/integrations/handlers/llama_index_handler/llama_index_handler.py
  mindsdb/integrations/handlers/rag_handler/requirements.txt
  tests/scripts/check_requirements.py
Labels: deploy-to-dev

#8705 installation docs updates
  docs/contribute/install.mdx
  docs/integrations/integrations.mdx
  docs/mindsdb_sql/sql/create/jobs.mdx
  docs/mint.json
  docs/setup/self-hosted/docker.mdx
Labels: documentation

#8706 updated ai tables doc page
  docs/generative-ai-tables.mdx
  docs/mindsdb_sql/sql/api/join.mdx
  docs/mindsdb_sql/sql/get-batch-predictions.mdx
Labels: documentation
