Repository mindsdb/mindsdb, pull requests merged in 2024-10, with the labels that each got.

#9809 docs: mindsdb custom auth
  docs/setup/custom-config.mdx
Labels: documentation

#9961 cache to main for staging and prod builds
  .github/workflows/build_deploy_prod.yml
  .github/workflows/build_deploy_staging.yml
Labels: deploy-to-alpha-dev

#9931 updated js sdk docs
  docs/sdks/javascript/finetune.mdx
Labels: documentation

#9943 Jssdk delete model
  docs/sdks/javascript/drop_model.mdx
Labels: documentation

#9963 docs for js sdk remove a view
  docs/sdks/javascript/drop_view.mdx
Labels: documentation

#9932 tutorial - build ai agents
  docs/mint.json
  docs/use-cases/ai_agents/build_ai_agents.mdx
Labels: documentation

#9986 docs updates
  docs/integrations/app-integrations/slack.mdx
  docs/sdks/javascript/list_views.mdx
Labels: documentation

#9991 docs for knowledge bases with usage examples
  docs/mindsdb_sql/agents/knowledge-bases.mdx
Labels: documentation

#10083 updated twilio tutorial image
  docs/assets/twilio-chatbot-diagram.png
Labels: documentation

#9976 Feature: Add Open Telemetry to MindsDB
  docker-compose.yml
  mindsdb/api/http/initialize.py
  mindsdb/utilities/otel.py
  requirements/requirements.txt
  tests/scripts/check_requirements.py
Labels: deploy-to-dev

#10086 Fix batch processor added to trace in Open Telemetry
  mindsdb/utilities/otel.py
Labels: deploy-to-dev

#10097 Run integration tests on proper branch
  .github/workflows/build_deploy_dev.yml
  .github/workflows/test_on_deploy.yml
Labels: deploy-to-alpha-dev

#10075 Fixed the Integration Tests for the Files Integration
  mindsdb/integrations/handlers/file_handler/tests/test_file_handler.py
Labels: deploy-to-dev

#10094 docs - removed 3.8 version of python
  docs/contribute/install.mdx
Labels: documentation
