Repository mindsdb/mindsdb, pull requests merged in 2024-11, with the labels that each got.

#9783 Speed up CI/CD workflows with UV
  .dockerignore
  .github/workflows/build_deploy_prod.yml
  .github/workflows/test_on_deploy.yml
  .github/workflows/test_on_push.yml
  docker/mindsdb.Dockerfile
  mindsdb/integrations/handlers/elasticsearch_handler/requirements.txt
Labels: deploy-to-alpha-dev

#10106 Format Langchain Objects Properly
  mindsdb/interfaces/agents/langchain_agent.py
Labels: deploy-to-dev

#10105 Update internal mysql protocol to be compatible with `mysql 9.1`
  .github/workflows/test_on_deploy.yml
  mindsdb/api/executor/command_executor.py
  mindsdb/api/mysql/mysql_proxy/utilities/exceptions.py
  mindsdb/integrations/handlers/mysql_handler/mysql_handler.py
  tests/integration_tests/flows/test_mysql_api.py
Labels: deploy-to-dev

#10109 Adding new user and session id into traces for langfuse
  mindsdb/api/http/initialize.py
  mindsdb/interfaces/agents/langchain_agent.py
  mindsdb/utilities/context.py
  requirements/requirements.txt
Labels: deploy-to-dev

#10101 updated chatbot sql docs
  docs/mindsdb_sql/agents/chatbot.mdx
  docs/openapi.yml
Labels: documentation

#10128 fix venvs in docker
  docker/mindsdb.Dockerfile
Labels: deploy-to-alpha-dev

#10140 Upgrade langchain 0.3.x
  mindsdb/integrations/handlers/dspy_handler/requirements.txt
  mindsdb/integrations/handlers/file_handler/file_handler.py
  mindsdb/integrations/handlers/langchain_embedding_handler/langchain_embedding_handler.py
  mindsdb/integrations/handlers/langchain_embedding_handler/requirements.txt
  mindsdb/integrations/handlers/langchain_handler/langchain_handler.py
  mindsdb/integrations/handlers/langchain_handler/requirements.txt
  mindsdb/integrations/handlers/langchain_handler/tools.py
  mindsdb/integrations/handlers/openai_handler/requirements.txt
  mindsdb/integrations/handlers/rag_handler/ingest.py
  mindsdb/integrations/handlers/rag_handler/requirements.txt
  mindsdb/integrations/handlers/rag_handler/settings.py
  mindsdb/integrations/handlers/writer_handler/settings.py
  mindsdb/integrations/libs/llm/utils.py
  mindsdb/integrations/utilities/rag/loaders/file_loader.py
  mindsdb/integrations/utilities/rag/rag_pipeline_builder.py
  mindsdb/integrations/utilities/rag/rerankers/reranker_compressor.py
  mindsdb/integrations/utilities/rag/settings.py
  mindsdb/interfaces/agents/callback_handlers.py
  mindsdb/interfaces/agents/langchain_agent.py
  mindsdb/interfaces/agents/mindsdb_chat_model.py
  mindsdb/interfaces/agents/mindsdb_database_agent.py
  mindsdb/interfaces/skills/custom/text2sql/mindsdb_sql_tool.py
  mindsdb/interfaces/skills/retrieval_tool.py
  mindsdb/interfaces/skills/skill_tool.py
  requirements/requirements-test.txt
  requirements/requirements.txt
  tests/scripts/check_requirements.py
Labels: deploy-to-dev

#10141 Option to return all handlers' schemas
  mindsdb/api/http/namespaces/tree.py
  mindsdb/integrations/handlers/postgres_handler/postgres_handler.py
Labels: deploy-to-dev

#10150 docs: js sdk alternative syntax for es6 module
  docs/sdks/javascript/connect.mdx
  docs/sdks/javascript/list_databases.mdx
Labels: documentation

#10148 docs: added the no-studio flag
  docs/contribute/install.mdx
  docs/mindsdb_sql/connect/mysql-client.mdx
  docs/mindsdb_sql/connect/postgres-client.mdx
  docs/setup/custom-config.mdx
  docs/setup/self-hosted/pip/linux.mdx
  docs/setup/self-hosted/pip/macos.mdx
  docs/setup/self-hosted/pip/source.mdx
  docs/setup/self-hosted/pip/windows.mdx
Labels: documentation

#10152 Improve `POST /databases` endpoint
  docs/integrations/app-integrations/microsoft-onedrive.mdx
  mindsdb/api/http/namespaces/databases.py
  mindsdb/integrations/handlers/ms_one_drive_handler/ms_one_drive_handler.py
Labels: deploy-to-dev

#10186 docs: mindsdb custom config explanation
  docs/setup/custom-config.mdx
  docs/setup/environment-vars.mdx
Labels: documentation

#10205 MySQL API memory optimisation
  mindsdb/__main__.py
  mindsdb/api/executor/datahub/datanodes/integration_datanode.py
  mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
  mindsdb/integrations/handlers/snowflake_handler/snowflake_handler.py
  mindsdb/interfaces/database/integrations.py
  mindsdb/utilities/config.py
  tests/integration_tests/flows/test_mysql_api.py
Labels: deploy-to-dev
