Repository mindsdb/mindsdb, pull requests merged in 2024-09, with the labels that each got.

#9671 langchain provider litellm update
  docs/integrations/ai-engines/langchain.mdx
Labels: documentation

#9693 added faq
  docs/faqs/missing-required-cpu-features.mdx
  docs/mint.json
Labels: documentation

#9692 Test: add py3.11 to tests matrix
  .github/workflows/matrix_includes.json
  setup.py
Labels: deploy-to-dev

#9711 fix docs mint.json
  docs/mint.json
Labels: documentation

#9736 Set pymongo requirement == 4.8.0
  mindsdb/__about__.py
  requirements/requirements.txt
Labels: deploy-to-dev

#9755 Add Flush to Langfuse & Handle Errors Properly for Getting Traces
  mindsdb/interfaces/agents/langchain_agent.py
  mindsdb/interfaces/agents/langfuse_callback_handler.py
Labels: bug, deploy-to-dev

#9764 removed obsolete rag handler from docs
  docs/integrations/ai-overview.mdx
  docs/integrations/support.mdx
  docs/use-cases/ai-powered_data_retrieval/semantic_search.mdx
Labels: documentation

#9756 Feature: Add sentry monitoring
  docker-compose.yml
  mindsdb/__main__.py
  mindsdb/api/http/initialize.py
  mindsdb/interfaces/jobs/scheduler.py
  mindsdb/utilities/ml_task_queue/consumer.py
  mindsdb/utilities/ml_task_queue/producer.py
  mindsdb/utilities/ml_task_queue/utils.py
  mindsdb/utilities/sentry.py
  requirements/requirements.txt
Labels: deploy-to-dev

#9765 updated rayserve docs
  docs/integrations/ai-engines/ray-serve.mdx
Labels: documentation
