Repository mindsdb/mindsdb, pull requests merged in 2025-01, with the labels that each got.

#10318 Feat/update otel configs
  .gitignore
  docker-compose.yml
  docs/setup/open_telemetry.mdx
  mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
  mindsdb/utilities/context.py
  mindsdb/utilities/log.py
  mindsdb/utilities/otel.py
  mindsdb/utilities/otel/__init__.py
  mindsdb/utilities/otel/logger.py
  mindsdb/utilities/otel/meter.py
  mindsdb/utilities/otel/metric_handlers/__init__.py
  mindsdb/utilities/otel/tracer.py
  mindsdb/utilities/utils.py
  otel-collector-config.yaml
  requirements/requirements.txt
  tests/scripts/check_requirements.py
Labels: deploy-to-dev

#10377 docs - mongodb connection params updated
  docs/integrations/data-integrations/mongodb.mdx
Labels: documentation

#10375 docs: join-on updates
  docs/mindsdb_sql/sql/api/join-on.mdx
Labels: documentation

#10372 Fixed Several Broken Integration Tests
  mindsdb/integrations/handlers/file_handler/tests/test_file_handler.py
  tests/integration_tests/flows/test_http.py
Labels: deploy-to-dev

#10380 docs - data overview logo
  docs/integrations/data-overview.mdx
Labels: documentation

#10374 Use new dispatch-and-wait workflow
  .github/workflows/deploy.yml
Labels: deploy-to-alpha-dev

#10384 Run auto-reload on devel container by default.
  docker-compose.yml
  docker/mindsdb.Dockerfile
Labels: deploy-to-alpha-dev

#10262 Refactor Langfuse Client
  docker-compose.yml
  mindsdb/interfaces/agents/agents_controller.py
  mindsdb/interfaces/agents/langchain_agent.py
  mindsdb/interfaces/agents/langfuse_callback_handler.py
  mindsdb/utilities/context.py
  mindsdb/utilities/langfuse.py
Labels: deploy-to-dev

#10388 fix: add trace_id
  mindsdb/api/http/namespaces/agents.py
  mindsdb/interfaces/agents/constants.py
  mindsdb/interfaces/agents/langchain_agent.py
  mindsdb/interfaces/agents/langfuse_callback_handler.py
  mindsdb/utilities/langfuse.py
Labels: deploy-to-dev, deploy-to-alpha-dev

#10394 Handle tables with dots in names in agents.
  mindsdb/api/executor/datahub/datanodes/integration_datanode.py
  mindsdb/integrations/handlers/databricks_handler/requirements.txt
  mindsdb/integrations/utilities/handlers/auth_utilities/microsoft/ms_graph_api_auth_utilities.py
  mindsdb/interfaces/agents/langchain_agent.py
  mindsdb/interfaces/agents/mindsdb_database_agent.py
  mindsdb/interfaces/skills/custom/text2sql/mindsdb_sql_toolkit.py
  mindsdb/interfaces/skills/skill_tool.py
  mindsdb/interfaces/skills/sql_agent.py
Labels: deploy-to-dev

#10415 Fix agent snowflake sql skill: table names in upper case
  mindsdb/interfaces/skills/skill_tool.py
Labels: deploy-to-dev

#10386 KB: filter by distance
  mindsdb/integrations/libs/vectordatabase_handler.py
  mindsdb/interfaces/knowledge_base/controller.py
Labels: deploy-to-dev

#10412 Fix issues with agents
  mindsdb/interfaces/agents/mindsdb_database_agent.py
  mindsdb/interfaces/skills/custom/text2sql/mindsdb_sql_toolkit.py
  mindsdb/interfaces/skills/skill_tool.py
  mindsdb/interfaces/skills/sql_agent.py
Labels: deploy-to-dev
