Repository mindsdb/mindsdb, pull requests merged in 2025-04, with the labels that each got.

#10628 Add KB to the projects tree list
  mindsdb/interfaces/database/projects.py
Labels: deploy-to-dev

#10642 docs mcp video
  docs/mcp/cursor_usage.mdx
Labels: documentation

#10648 mcp api docs -- docker command
  docs/mcp/overview.mdx
Labels: documentation

#10654 Make pushing docker cache a separate step
  .github/workflows/build_deploy_dev.yml
  .github/workflows/build_deploy_prod.yml
  .github/workflows/build_deploy_staging.yml
  docker/docker-bake.hcl
Labels: deploy-to-alpha-dev

#10664 docs mcp ports fix
  docs/mcp/overview.mdx
Labels: documentation

#10599 Run query in partitions
  mindsdb/api/executor/command_executor.py
  mindsdb/api/executor/datahub/datanodes/information_schema_datanode.py
  mindsdb/api/executor/datahub/datanodes/mindsdb_tables.py
  mindsdb/api/executor/planner/plan_join.py
  mindsdb/api/executor/planner/query_plan.py
  mindsdb/api/executor/planner/query_planner.py
  mindsdb/api/executor/planner/steps.py
  mindsdb/api/executor/sql_query/sql_query.py
  mindsdb/api/executor/sql_query/steps/__init__.py
  mindsdb/api/executor/sql_query/steps/fetch_dataframe_partition.py
  mindsdb/api/mysql/mysql_proxy/libs/constants/mysql.py
  mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
  mindsdb/integrations/handlers/pgvector_handler/pgvector_handler.py
  mindsdb/integrations/handlers/postgres_handler/postgres_handler.py
  mindsdb/interfaces/knowledge_base/controller.py
  mindsdb/interfaces/query_context/context_controller.py
  mindsdb/interfaces/storage/db.py
  mindsdb/migrations/versions/2025-03-21_fda503400e43_queries.py
  mindsdb/utilities/context_executor.py
  mindsdb/utilities/partitioning.py
  tests/integration_tests/flows/test_mysql_api.py
  tests/unit/executor/test_agent.py
  tests/unit/handlers/test_postgres.py
Labels: deploy-to-dev

#10679 docs - updated favicon
  docs/favicon.png
Labels: documentation

#10678 docs - fixed variable name
  README.md
  docs/what-is-mindsdb.mdx
Labels: documentation

#10686 updated mindsdb messaging
  README.md
  docs/what-is-mindsdb.mdx
Labels: documentation

#10649 kb docs
  docs/integrations/ai-engines/langchain_embedding.mdx
  docs/mindsdb_sql/agents/knowledge-bases.mdx
  docs/mindsdb_sql/sql/create/ml-engine.mdx
  docs/mint.json
Labels: documentation

#10696 kb docs updates
  docs/mindsdb_sql/agents/knowledge-bases.mdx
Labels: documentation

#10700 docs for json file
  docs/integrations/files/json.mdx
Labels: documentation

#10708 kb docs updates
  docs/mindsdb_sql/knowledge-bases.mdx
  docs/mint.json
Labels: documentation

#10714 updated langchain docs
  docs/integrations/ai-engines/langchain.mdx
  mindsdb/integrations/handlers/langchain_handler/README.md
Labels: documentation

#10725 kb docs - provider update
  docs/mindsdb_sql/knowledge-bases.mdx
Labels: documentation

#10722 kb docs - reranking methods
  docs/mindsdb_sql/knowledge-bases.mdx
Labels: documentation

#10746 kb docs - id column
  docs/mindsdb_sql/knowledge-bases.mdx
Labels: documentation

#10765 docs fix - to markdown function
  docs/mint.json
Labels: documentation

#10767 kb docs refactor
  docs/integrations/app-integrations/microsoft-teams.mdx
  docs/mindsdb_sql/knowledge-bases.mdx
  docs/setup/custom-config.mdx
Labels: documentation

#10689 Run integration tests on deployed environment
  .github/workflows/build_deploy_dev.yml
  .github/workflows/test_on_deploy.yml
  .github/workflows/test_on_push.yml
  .gitignore
  Makefile
  docker/docker-bake.hcl
  docker/docker-compose-ci.yml
  mindsdb/utilities/config.py
  requirements/requirements-test.txt
  tests/README.md
  tests/data/movies.csv
  tests/data/test.html
  tests/data/test.pdf
  tests/data/test.txt
  tests/integration/__init__.py
  tests/integration/conftest.py
  tests/integration/flows/__init__.py
  tests/integration/flows/conftest.py
  tests/integration/flows/test_company_independent.py
  tests/integration/flows/test_http.py
  tests/integration/flows/test_ml_task_queue.py
  tests/integration/flows/test_mysql_api.py
  tests/integration/flows/test_ts_predictions.py
  tests/integration/knowledge_bases/data/seed.sql
  tests/integration/knowledge_bases/mindsdb_langchain_pgvector_integration_test.py
  tests/integration/knowledge_bases/test_kb_sql.py
  tests/integration/knowledge_bases/test_knowledge_bases.py
  tests/integration/metrics/test_metrics.py
  tests/integration/rag/test_rag_search_kwargs.py
  tests/integration/tutorials/__init__.py
  tests/integration/tutorials/test_forecast_quaterly_house_tutorial.py
  tests/integration/tutorials/test_home_rental_prices_tutorial.py
  tests/integration/tutorials/test_predict_text_sentiment_huggingface_tutorial.py
  tests/integration/tutorials/test_predict_text_sentiment_openai_tutorial.py
  tests/integration_tests/flows/config/cert.pem
  tests/integration_tests/flows/config/config.json
  tests/integration_tests/flows/config/docker_config.json
  tests/integration_tests/flows/conftest.py
  tests/integration_tests/flows/ps.py
  tests/integration_tests/flows/test_ml_task_queue.py
  tests/integration_tests/flows/test_mysql_api.py
  tests/integration_tests/flows/test_mysql_bin_api.py
  tests/integration_tests/flows/test_predict_text_sentiment_openai_tutorial.py
  tests/utils/config.py
  tests/utils/http_test_helpers.py
Labels: deploy-to-dev
