Repository mindsdb/mindsdb, pull requests merged in 2025-07, with the labels that each got.

#11215 Use parser tests with the same version as installed version
  .github/workflows/test_on_push.yml
Labels: deploy-to-dev

#11218 Improve MCP tools description
  mindsdb/api/mcp/start.py
Labels: deploy-to-dev

#11229 Fix KB reranker: show error, support gemini
  mindsdb/integrations/handlers/litellm_handler/litellm_handler.py
  mindsdb/integrations/utilities/rag/rerankers/base_reranker.py
  mindsdb/interfaces/knowledge_base/controller.py
  mindsdb/interfaces/knowledge_base/llm_client.py
Labels: deploy-to-dev

#11189 docs -- kb via rest api
  docs/docs.json
  docs/rest/knowledge_bases/create.mdx
  docs/rest/knowledge_bases/delete.mdx
  docs/rest/knowledge_bases/get.mdx
  docs/rest/knowledge_bases/insert.mdx
  docs/rest/knowledge_bases/list.mdx
  docs/rest/knowledge_bases/query.mdx
Labels: documentation

#11198 KB error messages
  mindsdb/interfaces/knowledge_base/controller.py
Labels: deploy-to-dev

#11176 Enabled Google Gemini Model Support in TO_MARKDOWN() Function
  docs/mindsdb_sql/functions/to_markdown_function.mdx
  mindsdb/interfaces/functions/controller.py
Labels: deploy-to-dev

#11244 docs -- url_file_upload into config.json
  docs/mindsdb_sql/sql/create/file.mdx
  docs/setup/custom-config.mdx
  docs/setup/my_config.json
Labels: documentation

#11233 Changed Config Update Behavior to Overwrite Default Model Parameters
  mindsdb/api/http/namespaces/config.py
  mindsdb/utilities/config.py
Labels: deploy-to-dev

#11250 docs -- evaluate kb updates to from_sql info
  docs/mindsdb_sql/knowledge-bases.mdx
Labels: documentation

#11251 docs -- logging config
  docs/setup/custom-config.mdx
Labels: documentation

#11253 Add SOQL Instructions to Data Catalog Meta Prompts
  mindsdb/integrations/handlers/salesforce_handler/constants.py
  mindsdb/integrations/handlers/salesforce_handler/salesforce_handler.py
Labels: deploy-to-writer-dev

#11221 adding keyword search
  mindsdb/integrations/handlers/pgvector_handler/pgvector_handler.py
  mindsdb/integrations/libs/keyword_search_base.py
  mindsdb/integrations/libs/vectordatabase_handler.py
  mindsdb/integrations/utilities/sql_utils.py
  mindsdb/interfaces/knowledge_base/controller.py
  tests/unit/various/test_knowledge_base_hybrid_search.py
Labels: deploy-to-dev

#11256 Fix Salesforce Data Catalog
  mindsdb/integrations/handlers/salesforce_handler/salesforce_handler.py
  mindsdb/integrations/handlers/salesforce_handler/salesforce_tables.py
Labels: deploy-to-dev

#11170 Fix a2a server: changed location of a2a config
  mindsdb/__main__.py
  mindsdb/api/http/namespaces/config.py
  mindsdb/utilities/config.py
  tests/unit/api/a2a/test_a2a_config.py
Labels: deploy-to-alpha-dev

#11276 docs -- kb models usage
  docs/mindsdb_sql/knowledge_bases/create.mdx
Labels: documentation

#11260 docs -- added litellm docs
  docs/docs.json
  docs/integrations/ai-engines/litellm.mdx
Labels: documentation

#11284 docs -- mindsdb as fqe
  docs/assets/mindsdb-fqe.png
  docs/docs.json
  docs/mindsdb-fqe.mdx
Labels: documentation

#11288 docs -- added * syntax for adding data to agents
  docs/mindsdb_sql/agents/agent_syntax.mdx
Labels: documentation

#11281 Downgrade UV
  .github/workflows/test_on_push.yml
Labels: deploy-to-dev

#11269 Fix/chan notify
  .github/workflows/build_deploy_prod.yml
  .github/workflows/build_deploy_staging.yml
Labels: deploy-to-alpha-dev

#11271 `IF NOT EXISTS` for `CREATE AGENT`
  mindsdb/api/executor/command_executor.py
  mindsdb/api/http/namespaces/agents.py
  mindsdb/interfaces/agents/agents_controller.py
  tests/unit/executor/test_agent.py
Labels: deploy-to-dev

#11275 KB: whitelist of embedding providers
  mindsdb/interfaces/knowledge_base/controller.py
  tests/unit/executor/test_agent.py
Labels: deploy-to-dev

#11274 Fix Salesforce Metadata
  mindsdb/integrations/handlers/salesforce_handler/salesforce_tables.py
Labels: deploy-to-dev

#11173 Fix `InterfaceError` for Snowflake Data Catalog stats
  mindsdb/interfaces/data_catalog/data_catalog_loader.py
Labels: deploy-to-dev

#11286 docs -- added sql algebra and examples to kb query docs
  docs/mindsdb_sql/knowledge_bases/query.mdx
Labels: documentation

#10882 Fixed a spelling issue in integrations.mdx
  docs/integrations/integrations.mdx
Labels: deploy-to-dev

#11178 Added Structured JSON response output from LLMs
  mindsdb/integrations/handlers/litellm_handler/litellm_handler.py
  mindsdb/interfaces/knowledge_base/evaluate.py
  mindsdb/interfaces/knowledge_base/llm_client.py
Labels: deploy-to-dev

#11195 Added support for search in Youtube integration
  mindsdb/integrations/handlers/youtube_handler/youtube_tables.py
Labels: deploy-to-dev

#11042 Update test_on_deploy.yml
  .github/workflows/test_on_deploy.yml
Labels: deploy-to-dev

#11279 Prevent template injection
  mindsdb/interfaces/knowledge_base/preprocessing/document_preprocessor.py
Labels: deploy-to-dev

#11246 Only Load Explicitly Included Tables for Salesforce Data Catalog
  mindsdb/integrations/handlers/salesforce_handler/constants.py
  mindsdb/integrations/handlers/salesforce_handler/salesforce_handler.py
  mindsdb/integrations/handlers/salesforce_handler/salesforce_tables.py
  mindsdb/interfaces/agents/agents_controller.py
  tests/unit/handlers/test_salesforce.py
Labels: deploy-to-dev

#11294 Web handler: accept user-agent
  mindsdb/integrations/handlers/web_handler/urlcrawl_helpers.py
  mindsdb/integrations/handlers/web_handler/web_handler.py
Labels: deploy-to-dev

#11312 add preprocessing field to KnowledgeBase controller
  mindsdb/integrations/utilities/handler_utils.py
  mindsdb/interfaces/knowledge_base/controller.py
Labels: deploy-to-dev

#11259 KB integration test in CI
  mindsdb/integrations/handlers/chromadb_handler/chromadb_handler.py
  mindsdb/integrations/handlers/pgvector_handler/pgvector_handler.py
  mindsdb/integrations/libs/vectordatabase_handler.py
  mindsdb/interfaces/knowledge_base/controller.py
  mindsdb/interfaces/knowledge_base/evaluate.py
  mindsdb/interfaces/variables/variables_controller.py
  tests/integration/flows/test_knowledge_base.py
  tests/unit/executor/test_agent.py
  tests/unused/integration/knowledge_bases/test_kb_sql.py
Labels: deploy-to-dev

#11317 adding escaping for double quotes in the code
  mindsdb/integrations/handlers/pgvector_handler/pgvector_handler.py
Labels: deploy-to-dev

#11320 Fix staging integration tests
  .github/workflows/test_on_deploy.yml
Labels: deploy-to-alpha-dev

#11325 Pgvector: render queries with sqlalchemy render
  mindsdb/integrations/handlers/pgvector_handler/pgvector_handler.py
Labels: deploy-to-dev

#11323 Improve bigquery connection method
  mindsdb/api/http/initialize.py
  mindsdb/integrations/handlers/bigquery_handler/bigquery_handler.py
Labels: deploy-to-dev

#11316 adding alpha blending
  mindsdb/interfaces/knowledge_base/controller.py
Labels: deploy-to-dev

#11328 Replace deprecated `psutil.Process().connections()` to `net_connections()`
  mindsdb/utilities/ps.py
Labels: deploy-to-dev

#11302 docs -- to_markdown updates
  docs/mindsdb_sql/functions/to_markdown_function.mdx
Labels: documentation

#11255 Updated the REST API Endpoints for Agents
  mindsdb/api/http/namespaces/agents.py
  mindsdb/interfaces/agents/agents_controller.py
  mindsdb/interfaces/storage/db.py
  tests/unit/api/http/agents_test.py
  tests/unit/executor/test_agent.py
Labels: deploy-to-alpha-dev

#11348 docs - kb docs fix
  docs/mindsdb_sql/knowledge_bases/query.mdx
Labels: documentation

#11344 Fix tests
  tests/integration/flows/test_knowledge_base.py
Labels: deploy-to-dev

#11357 Adapt operators `is` and `is not` for salesforce handler
  docs/docs.json
  docs/integrations/ai-engines/anyscale.mdx
  docs/integrations/ai-engines/langchain.mdx
  docs/integrations/ai-overview.mdx
  docs/integrations/support.mdx
  docs/mindsdb_sql/functions/llm_function.mdx
  docs/mindsdb_sql/sql/api/finetune.mdx
  docs/sitemaps/use_cases.mdx
  docs/use-cases/automated_finetuning/anyscale.mdx
  docs/use-cases/automated_finetuning/overview.mdx
  mindsdb/api/executor/sql_query/steps/apply_predictor_step.py
  mindsdb/api/http/initialize.py
  mindsdb/api/http/namespaces/jobs.py
  mindsdb/api/http/namespaces/tree.py
  mindsdb/integrations/handlers/langchain_handler/langchain_handler.py
  mindsdb/integrations/handlers/salesforce_handler/salesforce_tables.py
  mindsdb/interfaces/agents/agents_controller.py
  mindsdb/interfaces/agents/langchain_agent.py
  tests/integration/flows/test_knowledge_base.py
  tests/unit/executor/test_agent.py
Labels: deploy-to-dev

#11361 Fix/staging wf
  .github/workflows/build_deploy_staging.yml
Labels: deploy-to-dev

#11368 Fixed Truth Value Evaluation for NumPy Arrays
  mindsdb/api/mysql/mysql_proxy/utilities/dump.py
Labels: deploy-to-dev

#11370 docs -- updated quickstart tutorial
  docs/quickstart-tutorial.mdx
Labels: documentation

#11329 Refactored the Logic for Updating Agents to Run Data Catalog Loader
  mindsdb/interfaces/agents/agents_controller.py
  mindsdb/interfaces/data_catalog/data_catalog_loader.py
Labels: deploy-to-alpha-dev

#11360 docs -- kb intro update
  docs/mindsdb_sql/knowledge_bases/overview.mdx
Labels: documentation

#11382 Remove anyscale
  mindsdb/integrations/handlers/anyscale_endpoints_handler/README.md
  mindsdb/integrations/handlers/anyscale_endpoints_handler/__about__.py
  mindsdb/integrations/handlers/anyscale_endpoints_handler/__init__.py
  mindsdb/integrations/handlers/anyscale_endpoints_handler/anyscale_endpoints_handler.py
  mindsdb/integrations/handlers/anyscale_endpoints_handler/creation_args.py
  mindsdb/integrations/handlers/anyscale_endpoints_handler/icon.svg
  mindsdb/integrations/handlers/anyscale_endpoints_handler/requirements.txt
  mindsdb/integrations/handlers/anyscale_endpoints_handler/settings.py
  mindsdb/integrations/handlers/anyscale_endpoints_handler/tests/__init__.py
  mindsdb/integrations/handlers/anyscale_endpoints_handler/tests/test_anyscale_endpoints_handler.py
  mindsdb/integrations/handlers/langchain_handler/README.md
  mindsdb/integrations/handlers/langchain_handler/langchain_handler.py
  mindsdb/integrations/libs/llm/config.py
  mindsdb/integrations/libs/llm/utils.py
  mindsdb/interfaces/agents/constants.py
  mindsdb/interfaces/agents/langchain_agent.py
  tests/unused/unit/ml_handlers/test_anyscale_endpoints.py
  tests/unused/unit/ml_handlers/test_langchain.py
Labels: deploy-to-dev

#11387 docs -- rename mcp
  docs/docs.json
  docs/model-context-protocol/anthropic.mdx
  docs/model-context-protocol/cursor_usage.mdx
  docs/model-context-protocol/openai.mdx
  docs/model-context-protocol/overview.mdx
  docs/model-context-protocol/usage.mdx
Labels: documentation
