Repository mindsdb/mindsdb, pull requests merged in 2025-02, with the labels that each got.

#10414 File handling in utilities
  mindsdb/integrations/handlers/file_handler/file_handler.py
  mindsdb/integrations/handlers/file_handler/tests/test_file_handler.py
  mindsdb/integrations/handlers/ms_one_drive_handler/ms_one_drive_tables.py
  mindsdb/integrations/utilities/files/file_reader.py
  mindsdb/integrations/utilities/handlers/api_utilities/microsoft/ms_graph_api_utilities.py
  mindsdb/interfaces/file/file_controller.py
Labels: deploy-to-dev

#10467 added link to minds
  README.md
  docs/minds-demo.mdx
  docs/mint.json
Labels: documentation

#10453 docs for partition_size support
  docs/mindsdb_sql/sql/get-batch-predictions.mdx
  docs/sdks/python/agents_knowledge_bases.mdx
  docs/sdks/python/get-batch-predictions.mdx
Labels: documentation

#10475 Fix an issue with pymupdf. Set it to 1.25.2
  requirements/requirements.txt
Labels: deploy-to-dev

#10493 docs: changed predictor to model
  docs/integrations/data-integrations/airtable.mdx
  docs/integrations/data-integrations/google-sheets.mdx
  docs/mindsdb_sql/sql/create/model.mdx
  docs/sql/feature-eng.mdx
  docs/use-cases/in-database_ml/byom.mdx
  docs/use-cases/in-database_ml/mindsdb-superset-snowflake.mdx
Labels: documentation

#10463 Metadata v3
  mindsdb/integrations/utilities/pydantic_utils.py
  mindsdb/integrations/utilities/rag/pipelines/rag.py
  mindsdb/integrations/utilities/rag/retrievers/sql_retriever.py
  mindsdb/integrations/utilities/rag/settings.py
Labels: deploy-to-dev

#10525 Metadata v3 (#10463)
  mindsdb/integrations/utilities/pydantic_utils.py
  mindsdb/integrations/utilities/rag/pipelines/rag.py
  mindsdb/integrations/utilities/rag/retrievers/sql_retriever.py
  mindsdb/integrations/utilities/rag/settings.py
Labels: deploy-to-alpha-dev

#10523 added try demo button
  docs/mint.json
Labels: documentation
