Repository mindsdb/mindsdb, pull requests merged in 2025-05, with the labels that each got.

#10784 Add test status catching job
  .github/workflows/build_deploy_dev.yml
  tests/integration/flows/test_mysql_api.py
  tests/integration/flows/test_ts_predictions.py
Labels: deploy-to-dev

#10790 dont use github cache on self hosted runners
  .github/workflows/test_on_deploy.yml
  .github/workflows/test_on_push.yml
Labels: deploy-to-dev

#10789 Fix getting tree for information_schema
  mindsdb/api/executor/datahub/datanodes/information_schema_datanode.py
  mindsdb/api/http/namespaces/tree.py
Labels: deploy-to-dev

#10782 Don't import integration_controller in main
  mindsdb/__main__.py
Labels: deploy-to-alpha-dev

#10817 use new ECR by default
  .github/workflows/build_deploy_dev.yml
  .github/workflows/test_on_push.yml
  docker/docker-bake.hcl
  mindsdb/integrations/handlers/lightwood_handler/requirements.txt
  mindsdb/integrations/handlers/openai_handler/openai_handler.py
  requirements/requirements-test.txt
  requirements/requirements.txt
  tests/integration/flows/test_http.py
  tests/integration/flows/test_mysql_api.py
  tests/integration/tutorials/test_predict_text_sentiment_openai_tutorial.py
  tests/scripts/check_requirements.py
  tests/unit/broken/test_mssql.py
Labels: deploy-to-dev

#10794 Fixed Incorrect Provider in Documentation for KB and Custom Configuration
  docs/mindsdb_sql/knowledge-bases.mdx
  docs/setup/custom-config.mdx
  tests/integration/flows/test_http.py
  tests/integration/flows/test_mysql_api.py
  tests/integration/tutorials/test_predict_text_sentiment_openai_tutorial.py
Labels: deploy-to-alpha-dev

#10811 Enabled AZURE_OPENAI_KEY for Azure Provider for Embedding Models in Knowledge Bases
  mindsdb/interfaces/knowledge_base/controller.py
Labels: deploy-to-alpha-dev

#10804 Added Support for HASH() and TO_MARKDOWN() as Built-in Functions in Query Planner
  mindsdb/api/executor/planner/query_planner.py
  tests/unit/planner/test_integration_select.py
Labels: deploy-to-alpha-dev

#10808 Generate KB row ID if not provided
  mindsdb/interfaces/knowledge_base/controller.py
  mindsdb/interfaces/knowledge_base/preprocessing/document_preprocessor.py
  mindsdb/interfaces/knowledge_base/utils.py
  tests/unit/executor/test_agent.py
  tests/unit/various/test_document_preprocessor.py
Labels: deploy-to-alpha-dev

#10798 Added Support for Complex Query Execution in Knowledge Bases
  mindsdb/interfaces/knowledge_base/controller.py
  tests/integration/knowledge_bases/test_kb_sql.py
Labels: deploy-to-alpha-dev

#10806 Optimizations of startup time and RAM usage
  MANIFEST.in
  docker/docker-bake.hcl
  docs/setup/open_telemetry.mdx
  mindsdb/__main__.py
  mindsdb/api/executor/command_executor.py
  mindsdb/api/executor/sql_query/steps/apply_predictor_step.py
  mindsdb/api/http/initialize.py
  mindsdb/api/http/namespaces/analysis.py
  mindsdb/api/mysql/mysql_proxy/classes/sql_statement_parser.py
  mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
  mindsdb/api/mysql/mysql_proxy/utilities/exceptions.py
  mindsdb/api/postgres/postgres_proxy/postgres_packets/postgres_message_formats.py
  mindsdb/integrations/handlers/lightfm_handler/requirements.txt
  mindsdb/integrations/handlers/lightwood_handler/lightwood_handler.py
  mindsdb/interfaces/agents/constants.py
  mindsdb/interfaces/agents/langchain_agent.py
  mindsdb/interfaces/database/projects.py
  mindsdb/interfaces/model/model_controller.py
  mindsdb/migrations/migrate.py
  mindsdb/utilities/context.py
  mindsdb/utilities/langfuse.py
  mindsdb/utilities/otel/__init__.py
  mindsdb/utilities/otel/metric_handlers/__init__.py
  mindsdb/utilities/otel/prepare.py
  mindsdb/utilities/sql.py
  requirements/requirements-langfuse.txt
  requirements/requirements-opentelemetry.txt
  requirements/requirements.txt
  setup.py
  tests/scripts/check_requirements.py
  tests/unit/various/test_utils_sql.py
Labels: deploy-to-dev

#10818 kb docs intro
  docs/mindsdb_sql/knowledge-bases.mdx
Labels: documentation, deploy-to-dev

#10830 Support py 3.12
  requirements/requirements.txt
  setup.py
  tests/integration/tutorials/test_forecast_quaterly_house_tutorial.py
  tests/integration/tutorials/test_home_rental_prices_tutorial.py
Labels: deploy-to-dev

#10779 Updated the TO_MARKDOWN() Function to Use AIPDF
  .github/workflows/test_on_push.yml
  mindsdb/integrations/handlers/chromadb_handler/requirements.txt
  mindsdb/interfaces/functions/controller.py
  mindsdb/interfaces/functions/to_markdown.py
  requirements/requirements.txt
  tests/integration/flows/test_http.py
  tests/scripts/check_requirements.py
Labels: deploy-to-dev

#10795 Updated the Documentation for the TO_MARKDOWN() Function
  docs/mindsdb_sql/functions/to_markdown_function.mdx
Labels: deploy-to-alpha-dev

#10834 dont run tests on docs changes
  .github/workflows/build_deploy_dev.yml
  .github/workflows/test_on_deploy.yml
Labels: deploy-to-alpha-dev

#10833 Fix using agent with KB skill
  mindsdb/interfaces/knowledge_base/controller.py
Labels: deploy-to-alpha-dev

#10832 Fix Snowflake Cert issue
  mindsdb/integrations/handlers/lightwood_handler/requirements.txt
  mindsdb/integrations/handlers/snowflake_handler/requirements.txt
  requirements/requirements.txt
Labels: deploy-to-dev

#10837 Version bump
  mindsdb/__about__.py
Labels: deploy-to-dev

#10814 kb docs updates
  docs/mindsdb_sql/knowledge-bases.mdx
Labels: documentation

#10835 Overhauled the Jira Integration
  docker/docker-bake.hcl
  mindsdb/integrations/handlers/jira_handler/jira_handler.archived.py
  mindsdb/integrations/handlers/jira_handler/jira_handler.py
  mindsdb/integrations/handlers/jira_handler/jira_tables.py
  mindsdb/integrations/handlers/jira_handler/requirements.txt
Labels: deploy-to-alpha-dev

#10842 Fix testing on release
  .github/workflows/test_on_deploy.yml
Labels: deploy-to-alpha-dev

#10845 Ensure file buffer is flushed before closing in file upload
  mindsdb/api/http/namespaces/file.py
Labels: deploy-to-dev

#10847 Transformers optional
  mindsdb/integrations/handlers/huggingface_handler/requirements.txt
  mindsdb/integrations/handlers/huggingface_handler/requirements_cpu.txt
  requirements/requirements.txt
Labels: deploy-to-dev

#10846 Set uv in deploy action
  .github/workflows/build_deploy_prod.yml
Labels: deploy-to-dev

#10853 kb docs example update
  docs/mindsdb_sql/knowledge-bases.mdx
Labels: documentation

#10816 docs for agents and chatbots updates
  docs/mindsdb_sql/agents/agent.mdx
  docs/mindsdb_sql/agents/chatbot.mdx
Labels: documentation

#10850 add codeowners
  .github/CODEOWNERS
Labels: deploy-to-dev

#10856 Fixed Imports of Handler Utilities
  mindsdb/integrations/handlers/bigquery_handler/bigquery_handler.py
  mindsdb/integrations/handlers/bigquery_handler/tests/test_bigquery_handler.py
  mindsdb/integrations/handlers/gmail_handler/gmail_handler.py
  mindsdb/integrations/handlers/google_calendar_handler/google_calendar_handler.py
  mindsdb/integrations/handlers/ms_one_drive_handler/ms_one_drive_handler.py
  mindsdb/integrations/handlers/ms_teams_handler/ms_teams_handler.py
  mindsdb/integrations/handlers/vertex_handler/vertex_client.py
  mindsdb/integrations/handlers/youtube_handler/youtube_handler.py
  mindsdb/integrations/utilities/handlers/api_utilities/__init__.py
  mindsdb/integrations/utilities/handlers/auth_utilities/__init__.py
  tests/unit/handlers/test_bigquery.py
Labels: deploy-to-alpha-dev

#10859 Add transformers to main requirements
  mindsdb/integrations/handlers/huggingface_handler/requirements.txt
  mindsdb/integrations/handlers/huggingface_handler/requirements_cpu.txt
  requirements/requirements.txt
Labels: deploy-to-dev

#10854 Adding create index
  mindsdb/api/executor/command_executor.py
  mindsdb/integrations/handlers/pgvector_handler/pgvector_handler.py
  mindsdb/integrations/libs/vectordatabase_handler.py
  mindsdb/interfaces/knowledge_base/controller.py
  requirements/requirements.txt
Labels: deploy-to-dev

#10868 added copy to doc pages
  docs/docs.json
Labels: documentation

#10865 docs into connect/unify/respond sections
  docs/docs.json
  docs/mindsdb-connect.mdx
  docs/mindsdb-respond.mdx
  docs/mindsdb-unify.mdx
  docs/mindsdb.mdx
  docs/overview_sdks_apis.mdx
  docs/rest/overview.mdx
  docs/sdks/javascript/overview.mdx
  docs/sdks/mongo/mindsdb-mongo-ql-overview.mdx
  docs/sdks/python/overview.mdx
Labels: documentation

#10863 Add 'checkpoint' migration
  mindsdb/migrations/README.md
  mindsdb/migrations/migrate.py
  mindsdb/migrations/versions/2025-05-21_9f150e4f9a05_checkpoint_1.py
Labels: deploy-to-alpha-dev

#10871 docs files updates
  docs/assets/sql/add-file-to-mindsdb-cloud-2.png
  docs/assets/sql/add-file-to-mindsdb-cloud-3.png
  docs/assets/sql/add-file-to-mindsdb-cloud.png
  docs/assets/sql/upload_file1.png
  docs/assets/sql/upload_file2.png
  docs/mindsdb_sql/sql/create/file.mdx
Labels: documentation

#10870 docs langchain updates
  docs/integrations/ai-engines/langchain.mdx
Labels: documentation

#10877 temp hide agents docs
  docs/docs.json
  docs/mindsdb-respond.mdx
Labels: documentation

#10857 A2A server
  mindsdb/__main__.py
  mindsdb/api/a2a/README.md
  mindsdb/api/a2a/__init__.py
  mindsdb/api/a2a/__main__.py
  mindsdb/api/a2a/a2a_client.py
  mindsdb/api/a2a/agent.py
  mindsdb/api/a2a/common/__init__.py
  mindsdb/api/a2a/common/client/__init__.py
  mindsdb/api/a2a/common/client/card_resolver.py
  mindsdb/api/a2a/common/client/client.py
  mindsdb/api/a2a/common/server/__init__.py
  mindsdb/api/a2a/common/server/server.py
  mindsdb/api/a2a/common/server/task_manager.py
  mindsdb/api/a2a/common/server/utils.py
  mindsdb/api/a2a/common/types.py
  mindsdb/api/a2a/common/utils/in_memory_cache.py
  mindsdb/api/a2a/common/utils/push_notification_auth.py
  mindsdb/api/a2a/constants.py
  mindsdb/api/a2a/pyproject.toml
  mindsdb/api/a2a/run_a2a.py
  mindsdb/api/a2a/task_manager.py
  mindsdb/api/a2a/uv.lock
  mindsdb/api/http/initialize.py
  mindsdb/integrations/utilities/handler_utils.py
  mindsdb/interfaces/agents/agents_controller.py
  mindsdb/interfaces/agents/constants.py
  mindsdb/interfaces/agents/langchain_agent.py
  mindsdb/interfaces/agents/mindsdb_database_agent.py
  mindsdb/interfaces/skills/custom/text2sql/mindsdb_kb_tools.py
  mindsdb/interfaces/skills/custom/text2sql/mindsdb_sql_toolkit.py
  mindsdb/interfaces/skills/skill_tool.py
  mindsdb/interfaces/skills/sql_agent.py
  mindsdb/utilities/config.py
  mindsdb/utilities/starters.py
  requirements/requirements.txt
  tests/api/http/a2a_test.py
  tests/integration/a2a/__init__.py
  tests/integration/a2a/test_a2a_streaming.py
  tests/scripts/check_requirements.py
  tests/unit/api/__init__.py
  tests/unit/api/a2a/__init__.py
  tests/unit/api/a2a/streaming_test_client.py
  tests/unit/api/a2a/test_a2a_config.py
  tests/unit/api/a2a/test_streaming_verification.py
  tests/unit/interfaces/agents/test_api_key_handling.py
  tests/unit/interfaces/skills/custom/text2sql/test_mindsdb_kb_tools.py
Labels: deploy-to-dev

#10872 Allow `INSERT` without columns list
  mindsdb/api/executor/sql_query/steps/insert_step.py
  tests/unit/executor/test_executor.py
Labels: deploy-to-alpha-dev

#10886 bugfix: adding alter table query to set table dimension for index cre…
  mindsdb/integrations/handlers/pgvector_handler/pgvector_handler.py
Labels: deploy-to-dev

#10901 Update sample-database.mdx
  docs/integrations/sample-database.mdx
Labels: documentation

#10823 Add JSON chunking support for KB
  mindsdb/interfaces/knowledge_base/controller.py
  mindsdb/interfaces/knowledge_base/preprocessing/document_preprocessor.py
  mindsdb/interfaces/knowledge_base/preprocessing/json_chunker.py
  mindsdb/interfaces/knowledge_base/preprocessing/models.py
  tests/unit/various/test_json_chunker.py
Labels: deploy-to-dev

#10716 Improvements of column type mapping in the MySQL API.
  docs/integrations/data-integrations/oracle.mdx
  mindsdb/api/executor/command_executor.py
  mindsdb/api/executor/datahub/classes/response.py
  mindsdb/api/executor/datahub/datanodes/integration_datanode.py
  mindsdb/api/executor/sql_query/result_set.py
  mindsdb/api/executor/sql_query/sql_query.py
  mindsdb/api/executor/sql_query/steps/apply_predictor_step.py
  mindsdb/api/executor/sql_query/steps/fetch_dataframe.py
  mindsdb/api/executor/sql_query/steps/fetch_dataframe_partition.py
  mindsdb/api/executor/sql_query/steps/insert_step.py
  mindsdb/api/executor/sql_query/steps/join_step.py
  mindsdb/api/executor/sql_query/steps/project_step.py
  mindsdb/api/executor/sql_query/steps/sql_steps.py
  mindsdb/api/executor/sql_query/steps/subselect_step.py
  mindsdb/api/executor/sql_query/steps/union_step.py
  mindsdb/api/http/namespaces/analysis.py
  mindsdb/api/http/namespaces/sql.py
  mindsdb/api/mcp/start.py
  mindsdb/api/mysql/mysql_proxy/data_types/mysql_packet.py
  mindsdb/api/mysql/mysql_proxy/data_types/mysql_packets/binary_resultset_row_package.py
  mindsdb/api/mysql/mysql_proxy/executor/mysql_executor.py
  mindsdb/api/mysql/mysql_proxy/libs/constants/mysql.py
  mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
  mindsdb/api/mysql/mysql_proxy/utilities/dump.py
  mindsdb/api/postgres/postgres_proxy/executor/executor.py
  mindsdb/api/postgres/postgres_proxy/postgres_proxy.py
  mindsdb/integrations/handlers/mssql_handler/mssql_handler.py
  mindsdb/integrations/handlers/mysql_handler/mysql_handler.py
  mindsdb/integrations/handlers/oracle_handler/README.md
  mindsdb/integrations/handlers/oracle_handler/connection_args.py
  mindsdb/integrations/handlers/oracle_handler/oracle_handler.py
  mindsdb/integrations/handlers/postgres_handler/postgres_handler.py
  mindsdb/integrations/handlers/snowflake_handler/snowflake_handler.py
  mindsdb/integrations/libs/response.py
  tests/integration/flows/test_mysql_api.py
  tests/unit/executor/test_mongodb_server.py
  tests/unit/handlers/base_handler_test.py
  tests/unit/handlers/test_mariadb.py
  tests/unit/handlers/test_mysql.py
  tests/unit/handlers/test_oracle.py
  tests/unit/handlers/test_postgres.py
  tests/unit/handlers/test_snowflake.py
  tests/unit/various/test_dump_result_set_to_mysql.py
  tests/unused/unit/broken/test_mssql.py
Labels: deploy-to-dev

#10913 docs shortcut to mcp docs
  docs/docs.json
Labels: documentation

#10902 docs for agents
  docs/assets/mindsdb_gui_respond.png
  docs/assets/mindsdb_gui_respond_agents.png
  docs/assets/mindsdb_gui_respond_chat.png
  docs/docs.json
  docs/mindsdb-respond.mdx
  docs/mindsdb_sql/agents/agent.mdx
Labels: documentation

#10916 Use ruff for linting and formatting
  .flake8
  .github/CODEOWNERS
  .pre-commit-config.yaml
  pyproject.toml
  requirements/requirements-dev.txt
Labels: deploy-to-dev

#10919 Add A2A API support to configuration and Docker setup
  .gitignore
  Makefile
  docker-compose.yml
  docker/mindsdb.Dockerfile
  docker/mindsdb_config.release.json
  mindsdb/api/a2a/README.md
  mindsdb/api/a2a/__main__.py
  mindsdb/api/a2a/common/client/card_resolver.py
  mindsdb/api/a2a/common/client/client.py
  mindsdb/api/a2a/pyproject.toml
  mindsdb/api/a2a/run_a2a.py
  mindsdb/api/a2a/task_manager.py
  mindsdb/api/a2a/uv.lock
  mindsdb/utilities/config.py
  requirements/requirements.txt
  tests/scripts/check_requirements.py
  tests/unit/api/a2a/test_a2a_config.py
Labels: deploy-to-dev

#10923 Disabled Use of MindsDB Models for Knowledge Bases
  mindsdb/api/executor/command_executor.py
  mindsdb/interfaces/knowledge_base/controller.py
  tests/unit/executor/test_agent.py
  tests/unused/integration/knowledge_bases/test_kb_sql.py
Labels: deploy-to-alpha-dev

#10924 Add pyarrow to main requirements
  mindsdb/integrations/handlers/byom_handler/requirements.txt
  mindsdb/integrations/handlers/lancedb_handler/requirements.txt
  requirements/requirements.txt
Labels: deploy-to-dev

#10942 fix getting a2a config
  mindsdb/__about__.py
  mindsdb/api/a2a/run_a2a.py
  mindsdb/utilities/starters.py
Labels: deploy-to-dev

#10862 Data Catalog V1
  mindsdb/integrations/handlers/postgres_handler/postgres_handler.py
  mindsdb/integrations/libs/api_handler.py
  mindsdb/integrations/libs/base.py
  mindsdb/interfaces/data_catalog/__init__.py
  mindsdb/interfaces/data_catalog/base_data_catalog.py
  mindsdb/interfaces/data_catalog/data_catalog_loader.py
  mindsdb/interfaces/data_catalog/data_catalog_reader.py
  mindsdb/interfaces/database/integrations.py
  mindsdb/interfaces/skills/skills_controller.py
  mindsdb/interfaces/storage/db.py
  mindsdb/migrations/versions/2025-05-28_a44643042fe8_added_data_catalog_tables.py
  mindsdb/utilities/config.py
Labels: deploy-to-dev

#10941 adding empty reranking for kb controller
  mindsdb/interfaces/knowledge_base/controller.py
Labels: deploy-to-dev

#10952 infra: remove prod deploy
  .github/workflows/build_deploy_prod.yml
Labels: deploy-to-dev
