Repository mindsdb/mindsdb, pull requests merged in 2025-10, with the labels that each got.

#11639 Fixes Windows tests by pinning Numba version
  .github/workflows/tests_unit.yml
  docker/mindsdb.Dockerfile
  mindsdb/integrations/handlers/statsforecast_handler/requirements.txt
  mindsdb/integrations/handlers/statsforecast_handler/requirements_extra.txt
  tests/scripts/check_requirements.py
  tests/unit/various/test_arg_probing.py
Labels: deploy-to-alpha-dev

#11657 fix KB `GREATER THAN` filter
  mindsdb/interfaces/knowledge_base/controller.py
  tests/unit/executor/test_knowledge_base.py
Labels: deploy-to-dev

#11611 Unit tests for path traversal in files and byom
  mindsdb/api/http/namespaces/handlers.py
  tests/unit/api/http/byom_test.py
  tests/unit/api/http/files_test.py
Labels: deploy-to-dev

#11679 Rename `is_acceptable` to `is_expected`
  mindsdb/api/executor/datahub/datanodes/integration_datanode.py
  mindsdb/api/http/namespaces/sql.py
  mindsdb/integrations/handlers/postgres_handler/postgres_handler.py
  mindsdb/integrations/libs/response.py
  mindsdb/utilities/exception.py
Labels: deploy-to-dev

#11664 Custom Orjson for serialization
  mindsdb/api/executor/utilities/sql.py
  mindsdb/api/http/initialize.py
  mindsdb/api/mysql/mysql_proxy/utilities/dump.py
  mindsdb/interfaces/storage/db.py
  mindsdb/utilities/json_encoder.py
  requirements/requirements.txt
  tests/integration/flows/test_mysql_api.py
  tests/integration/utils/test_json_encoder.py
  tests/unit/utilities/test_json_encoder.py
Labels: deploy-to-dev

#11691 docs -- releases and contributing
  docs/contribute/community.mdx
  docs/contribute/contribute.mdx
  docs/contribute/docs-rules.mdx
  docs/contribute/docs.mdx
  docs/contribute/issue-labels.mdx
  docs/contribute/issues.mdx
  docs/contribute/tests.mdx
  docs/contribute/tutorials.mdx
  docs/docs.json
  docs/releases.mdx
Labels: documentation
