Repository mindsdb/mindsdb, pull requests merged in 2025-06, with the labels that each got.

#10944 Update skill for Data catalogue
  mindsdb/interfaces/agents/agents_controller.py
  mindsdb/interfaces/skills/skills_controller.py
Labels: deploy-to-dev

#10984 Show exception of LLM function
  mindsdb/api/executor/utilities/sql.py
Labels: deploy-to-dev

#10986 kb docs - create index on kb
  docs/mindsdb_sql/knowledge-bases.mdx
Labels: documentation

#10987 kb docs -- update for metadata
  docs/mindsdb_sql/knowledge-bases.mdx
Labels: documentation

#10914 Evaluate knowledge base
  mindsdb/api/executor/command_executor.py
  mindsdb/api/executor/datahub/datanodes/integration_datanode.py
  mindsdb/api/executor/sql_query/result_set.py
  mindsdb/integrations/handlers/litellm_handler/litellm_handler.py
  mindsdb/interfaces/knowledge_base/controller.py
  mindsdb/interfaces/knowledge_base/evaluate.py
  mindsdb/interfaces/knowledge_base/llm_client.py
Labels: deploy-to-dev

#10945 kb docs updates
  docs/assets/sql/kb_retrieval_example1.png
  docs/assets/sql/kb_retrieval_example2.png
  docs/assets/sql/kb_retrieval_example3.png
  docs/docs.json
  docs/mindsdb_sql/functions/from_env.mdx
  docs/mindsdb_sql/knowledge-bases.mdx
Labels: documentation

#11001 kb docs - provider name fix
  docs/mindsdb_sql/knowledge-bases.mdx
Labels: documentation

#10940 adding parameter to the select query to turn off reranking
  mindsdb/interfaces/knowledge_base/controller.py
Labels: deploy-to-dev

#11000 Fix file logging in Windows
  mindsdb/utilities/log.py
  mindsdb/utilities/starters.py
Labels: deploy-to-dev

#10996 Removed Database When Table Restriction Parameters are Used
  mindsdb/interfaces/agents/agents_controller.py
Labels: deploy-to-dev

#10951 Snowflake Data Catalogue
  mindsdb/integrations/handlers/snowflake_handler/snowflake_handler.py
Labels: deploy-to-dev

#10907 Added Support for ALTER VIEW
  mindsdb/api/executor/command_executor.py
  requirements/requirements.txt
  tests/unit/executor/test_executor.py
Labels: deploy-to-dev

#11007 remove github-actions pull secret
  .github/workflows/build_deploy_prod.yml
  .github/workflows/build_deploy_staging.yml
Labels: deploy-to-dev

#11006 Testing fixes
  mindsdb/utilities/config.py
  mindsdb/utilities/ml_task_queue/task.py
  tests/integration/flows/test_mysql_api.py
  tests/unit/render/test_from_parser.py
Labels: deploy-to-dev

#10906 Added Support for UPDATE DATABASE
  mindsdb/api/executor/command_executor.py
  mindsdb/interfaces/database/database.py
  tests/unit/executor/test_base_queires.py
Labels: deploy-to-dev

#11009 Add /status endpoint for A2A to provide server health information
  mindsdb/api/a2a/common/server/server.py
Labels: deploy-to-dev

#11017 enable auto migrations in cloud
  .github/workflows/add_to_pr_review.yml
  .github/workflows/add_to_roadmap_project_v2.yml
  .github/workflows/build_deploy_dev.yml
  .github/workflows/build_deploy_prod.yml
  .github/workflows/build_deploy_staging.yml
  .github/workflows/cla.yml
  .github/workflows/deploy.yml
  .github/workflows/release_notes.yml
  .github/workflows/test_on_deploy.yml
  .github/workflows/test_on_push.yml
  docker/docker-compose-ci.yml
Labels: deploy-to-dev

#11005 Add "a2a" key to config response in HTTP API
  mindsdb/api/http/namespaces/config.py
Labels: deploy-to-dev, deploy-to-alpha-dev

#11024 add more openai models for agents
  mindsdb/interfaces/agents/constants.py
Labels: deploy-to-dev

#11014 Enable Data Catalog Support for the New Agent Implementation
  mindsdb/interfaces/data_catalog/base_data_catalog.py
  mindsdb/interfaces/skills/skills_controller.py
  mindsdb/interfaces/skills/sql_agent.py
Labels: deploy-to-dev

#11020 Fixed Metadata Queries for Snowflake (Data Catalog)
  mindsdb/integrations/handlers/snowflake_handler/snowflake_handler.py
Labels: deploy-to-alpha-dev

#11031 a2a: add conversation history support to agent stream method
  docs/package-lock.json
  mindsdb/api/a2a/agent.py
Labels: deploy-to-dev

#11037 fix auto config not existing
  mindsdb/utilities/config.py
Labels: deploy-to-dev

#11022 Fix render of Cast function in select targets for BigQuery
  mindsdb/utilities/render/sqlalchemy_render.py
Labels: deploy-to-dev

#11021 Improved Reliability and Error Handling of Data Catalog Loader
  mindsdb/integrations/handlers/postgres_handler/postgres_handler.py
  mindsdb/interfaces/data_catalog/data_catalog_loader.py
  mindsdb/interfaces/skills/skills_controller.py
  mindsdb/interfaces/storage/db.py
  mindsdb/migrations/versions/2025-06-09_608e376c19a7_updated_data_catalog_data_types.py
Labels: deploy-to-dev

#11050 Fix Evaluate output: remove retrieved_in_top_k
  mindsdb/interfaces/knowledge_base/evaluate.py
Labels: deploy-to-dev

#11080 kb docs -- evaluate syntax
  docs/mindsdb_sql/knowledge-bases.mdx
Labels: documentation

#10947 Enabled Google BigQuery as a Supported Source in Data Catalog
  mindsdb/integrations/handlers/bigquery_handler/bigquery_handler.py
  mindsdb/integrations/libs/base.py
  mindsdb/interfaces/data_catalog/data_catalog_loader.py
Labels: deploy-to-writer-dev

#11077 Agent Salesforce fixes
  docs/integrations/app-integrations/salesforce.mdx
  mindsdb/integrations/handlers/salesforce_handler/salesforce_handler.py
  mindsdb/integrations/libs/api_handler.py
  mindsdb/interfaces/agents/agents_controller.py
  mindsdb/interfaces/data_catalog/data_catalog_reader.py
  mindsdb/interfaces/skills/skills_controller.py
  tests/integration/tutorials/test_predict_text_sentiment_huggingface_tutorial.py
Labels: deploy-to-writer-dev

#11102 Fix `ssl` option of mysql handler
  mindsdb/integrations/handlers/mysql_handler/mysql_handler.py
Labels: deploy-to-dev

#11079 kb docs -- added links to ai integrations
  docs/mindsdb_sql/knowledge-bases.mdx
Labels: documentation

#11110 New Release
  mindsdb/__about__.py
Labels: deploy-to-dev

#11099 Replace `locals()` to `connection.register` when register duckdb tables
  mindsdb/api/executor/utilities/sql.py
Labels: deploy-to-dev

#11127 Fixed Knowledge Base Insert Operations via SQL Queries and Raw Data
  mindsdb/interfaces/knowledge_base/controller.py
  mindsdb/interfaces/knowledge_base/preprocessing/document_loader.py
  tests/unused/unit/api/http/knowledge_bases_test.py
Labels: deploy-to-alpha-dev

#11117 Add Support for Stable Gemini 2.5 Models
  mindsdb/interfaces/agents/constants.py
Labels: deploy-to-dev

#11136 Fix agent with KB: strip input of kb_query_tool
  mindsdb/interfaces/skills/custom/text2sql/mindsdb_kb_tools.py
Labels: deploy-to-dev

#11135 Add default value and description for SF columns metadata
  mindsdb/integrations/handlers/salesforce_handler/salesforce_tables.py
Labels: deploy-to-dev

#11129 kb docs -- changed relevance_threshold into relevance
  docs/mindsdb_sql/knowledge-bases.mdx
Labels: documentation

#11139 docs for kbs -- removed ollama support
  docs/mindsdb_sql/knowledge-bases.mdx
Labels: documentation

#11121 Better error messages
  mindsdb/api/executor/datahub/datanodes/integration_datanode.py
  mindsdb/api/executor/datahub/datanodes/project_datanode.py
  mindsdb/api/executor/planner/plan_join.py
  mindsdb/api/executor/planner/query_planner.py
  requirements/requirements-test.txt
  tests/unit/render/test_from_parser.py
Labels: deploy-to-dev

#11111 Check table name in lower case in API Handler
  mindsdb/integrations/libs/api_handler.py
  tests/unit/handlers/test_salesforce.py
Labels: deploy-to-dev

#11161 Fixed Handling of Default Model Configuration Parameters
  mindsdb/interfaces/knowledge_base/controller.py
Labels: deploy-to-dev

#11155 Temporary disable `huggingface_handler`
  docker/docker-bake.hcl
  mindsdb/integrations/handlers/huggingface_handler/__init__.py
  mindsdb/integrations/handlers/huggingface_handler/finetune.py
  mindsdb/integrations/handlers/huggingface_handler/huggingface_handler.py
  mindsdb/integrations/handlers/huggingface_handler/requirements.txt
  mindsdb/integrations/handlers/huggingface_handler/requirements_cpu.txt
  mindsdb/integrations/handlers/huggingface_handler/settings.py
  requirements/requirements.txt
  tests/integration/tutorials/test_predict_text_sentiment_huggingface_tutorial.py
Labels: deploy-to-dev

#11131 Data Catlogue Docs
  docs/data_catalog/integrations/overview.mdx
  docs/data_catalog/integrations/query.mdx
  docs/data_catalog/overview.mdx
  docs/docs.json
  docs/setup/custom-config.mdx
  docs/setup/self-hosted/docker.mdx
Labels: documentation

#11175 Changes to `test_mysql_api.py` based on db driver features
  tests/integration/flows/test_mysql_api.py
Labels: deploy-to-dev

#11114 Adding keyword search
  mindsdb/integrations/handlers/pgvector_handler/pgvector_handler.py
  mindsdb/interfaces/knowledge_base/controller.py
Labels: deploy-to-dev

#11132 KB algebra
  mindsdb/integrations/handlers/chromadb_handler/chromadb_handler.py
  mindsdb/integrations/handlers/pgvector_handler/pgvector_handler.py
  mindsdb/integrations/libs/vectordatabase_handler.py
  mindsdb/interfaces/knowledge_base/controller.py
  mindsdb/interfaces/knowledge_base/executor.py
  tests/unit/executor/test_agent.py
Labels: deploy-to-dev

#11150 Fix Subscribe in PostgreSQL
  mindsdb/integrations/handlers/postgres_handler/postgres_handler.py
Labels: deploy-to-dev

#10939 KB metadata keys: service values are underscored
  mindsdb/interfaces/knowledge_base/controller.py
  mindsdb/interfaces/knowledge_base/preprocessing/document_preprocessor.py
  mindsdb/interfaces/knowledge_base/preprocessing/models.py
  tests/unit/executor/test_agent.py
  tests/unit/various/test_document_preprocessor.py
  tests/unit/various/test_json_chunker.py
Labels: deploy-to-dev

#11019 KB restrict filter by unknown metadata keys
  mindsdb/integrations/libs/vectordatabase_handler.py
  mindsdb/interfaces/knowledge_base/controller.py
  tests/unit/executor/test_agent.py
Labels: deploy-to-dev
